Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "E"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "E"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 240
WshShell.SendKeys "A"
Wscript.sleep 240
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "A"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "B"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "W"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "E"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "V"
Wscript.sleep 120
WshShell.SendKeys "B"
Wscript.sleep 120
WshShell.SendKeys "V"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 360
WshShell.SendKeys "W"
Wscript.sleep 60
WshShell.SendKeys "T"
Wscript.sleep 60
WshShell.SendKeys "S"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "X"
Wscript.sleep 420
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 840
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 960
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "E"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "E"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 240
WshShell.SendKeys "A"
Wscript.sleep 240
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "A"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "B"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "W"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "E"
Wscript.sleep 240
WshShell.SendKeys "T"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "V"
Wscript.sleep 120
WshShell.SendKeys "B"
Wscript.sleep 120
WshShell.SendKeys "V"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "C"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 360
WshShell.SendKeys "W"
Wscript.sleep 60
WshShell.SendKeys "T"
Wscript.sleep 60
WshShell.SendKeys "S"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "X"
Wscript.sleep 420
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 840
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "W"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "E"
Wscript.sleep 120
WshShell.SendKeys "Q"
Wscript.sleep 120
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 120
WshShell.SendKeys "S"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 240
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
Wscript.sleep 240
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 60
WshShell.SendKeys "G"
Wscript.sleep 60
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 240
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "D"
Wscript.sleep 120
WshShell.SendKeys "T"
Wscript.sleep 120
WshShell.SendKeys "Z"
Wscript.sleep 120
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
