Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 3680
WshShell.SendKeys "E"
Wscript.sleep 368
WshShell.SendKeys "T"
Wscript.sleep 368
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 736
WshShell.SendKeys "E"
Wscript.sleep 368
WshShell.SendKeys "T"
Wscript.sleep 368
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 736
WshShell.SendKeys "A"
Wscript.sleep 368
WshShell.SendKeys "G"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "G"
Wscript.sleep 368
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 736
WshShell.SendKeys "T"
Wscript.sleep 368
WshShell.SendKeys "E"
Wscript.sleep 368
WshShell.SendKeys "W"
Wscript.sleep 736
WshShell.SendKeys "W"
Wscript.sleep 368
WshShell.SendKeys "E"
Wscript.sleep 368
WshShell.SendKeys "W"
Wscript.sleep 552
WshShell.SendKeys "E"
Wscript.sleep 92
WshShell.SendKeys "W"
Wscript.sleep 92
WshShell.SendKeys "Q"
Wscript.sleep 368
WshShell.SendKeys "W"
Wscript.sleep 1472
WshShell.SendKeys "E"
Wscript.sleep 92
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 92
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "E"
Wscript.sleep 92
WshShell.SendKeys "W"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "S"
Wscript.sleep 92
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "C"
Wscript.sleep 92
WshShell.SendKeys "B"
Wscript.sleep 92
WshShell.SendKeys "C"
Wscript.sleep 276
WshShell.SendKeys "T"
Wscript.sleep 368
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 368
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 368
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 368
WshShell.SendKeys "B"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 368
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 1104
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 1104
WshShell.SendKeys "G"
Wscript.sleep 368
WshShell.SendKeys "X"
Wscript.sleep 368
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 368
WshShell.SendKeys "B"
Wscript.sleep 368
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 368
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 368
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 736
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "D"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 92
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 736
WshShell.SendKeys "G"
Wscript.sleep 368
WshShell.SendKeys "X"
Wscript.sleep 368
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "C"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "C"
Wscript.sleep 368
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "C"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 368
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "C"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 368
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 184
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 184
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "F"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 184
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "A"
Wscript.sleep 92
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "E"
Wscript.sleep 92
WshShell.SendKeys "W"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 92
WshShell.SendKeys "D"
Wscript.sleep 92
WshShell.SendKeys "S"
Wscript.sleep 92
WshShell.SendKeys "T"
Wscript.sleep 92
WshShell.SendKeys "E"
Wscript.sleep 184
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 92
WshShell.SendKeys "C"
Wscript.sleep 92
WshShell.SendKeys "B"
Wscript.sleep 92
WshShell.SendKeys "C"
