Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 668
WshShell.SendKeys "D"
Wscript.sleep 232
WshShell.SendKeys "F"
Wscript.sleep 223
WshShell.SendKeys "G"
Wscript.sleep 13
WshShell.SendKeys "Q"
Wscript.sleep 10
WshShell.SendKeys "E"
Wscript.sleep 244
WshShell.SendKeys "D"
Wscript.sleep 233
WshShell.SendKeys "X"
Wscript.sleep 708
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 13
WshShell.SendKeys "S"
Wscript.sleep 11
WshShell.SendKeys "T"
Wscript.sleep 488
WshShell.SendKeys "X"
Wscript.sleep 753
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 6
WshShell.SendKeys "D"
Wscript.sleep 39
WshShell.SendKeys "A"
Wscript.sleep 243
WshShell.SendKeys "A"
Wscript.sleep 285
WshShell.SendKeys "G"
Wscript.sleep 730
WshShell.SendKeys "D"
Wscript.sleep 226
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "S"
Wscript.sleep 971
WshShell.SendKeys "T"
Wscript.sleep 427
WshShell.SendKeys "D"
Wscript.sleep 14
WshShell.SendKeys "R"
Wscript.sleep 19
WshShell.SendKeys "A"
Wscript.sleep 506
WshShell.SendKeys "S"
Wscript.sleep 454
WshShell.SendKeys "D"
Wscript.sleep 223
WshShell.SendKeys "F"
Wscript.sleep 254
WshShell.SendKeys "E"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 506
WshShell.SendKeys "D"
Wscript.sleep 473
WshShell.SendKeys "F"
Wscript.sleep 242
WshShell.SendKeys "G"
Wscript.sleep 239
WshShell.SendKeys "T"
Wscript.sleep 16
WshShell.SendKeys "F"
Wscript.sleep 21
WshShell.SendKeys "Z"
Wscript.sleep 504
WshShell.SendKeys "Z"
Wscript.sleep 226
WshShell.SendKeys "G"
Wscript.sleep 240
WshShell.SendKeys "F"
Wscript.sleep 205
WshShell.SendKeys "D"
Wscript.sleep 236
WshShell.SendKeys "S"
Wscript.sleep 6
WshShell.SendKeys "F"
Wscript.sleep 916
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 226
WshShell.SendKeys "G"
Wscript.sleep 10
WshShell.SendKeys "E"
Wscript.sleep 19
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 230
WshShell.SendKeys "X"
Wscript.sleep 658
WshShell.SendKeys "G"
Wscript.sleep 202
WshShell.SendKeys "S"
Wscript.sleep 30
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "F"
Wscript.sleep 451
WshShell.SendKeys "X"
Wscript.sleep 778
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 34
WshShell.SendKeys "A"
Wscript.sleep 248
WshShell.SendKeys "A"
Wscript.sleep 211
WshShell.SendKeys "A"
Wscript.sleep 503
WshShell.SendKeys "S"
Wscript.sleep 274
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 66
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "W"
Wscript.sleep 854
WshShell.SendKeys "T"
Wscript.sleep 447
WshShell.SendKeys "D"
Wscript.sleep 16
WshShell.SendKeys "R"
Wscript.sleep 7
WshShell.SendKeys "A"
Wscript.sleep 468
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 226
WshShell.SendKeys "F"
Wscript.sleep 235
WshShell.SendKeys "E"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 470
WshShell.SendKeys "D"
Wscript.sleep 481
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 242
WshShell.SendKeys "W"
Wscript.sleep 7
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "F"
Wscript.sleep 512
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 223
WshShell.SendKeys "D"
Wscript.sleep 246
WshShell.SendKeys "D"
Wscript.sleep 215
WshShell.SendKeys "D"
Wscript.sleep 12
WshShell.SendKeys "E"
Wscript.sleep 12
WshShell.SendKeys "Q"
Wscript.sleep 1244
WshShell.SendKeys "D"
Wscript.sleep 473
WshShell.SendKeys "Q"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 1067
WshShell.SendKeys "D"
Wscript.sleep 538
WshShell.SendKeys "Q"
Wscript.sleep 8
WshShell.SendKeys "E"
Wscript.sleep 1167
WshShell.SendKeys "D"
Wscript.sleep 547
WshShell.SendKeys "Q"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 1009
WshShell.SendKeys "G"
Wscript.sleep 222
WshShell.SendKeys "Z"
Wscript.sleep 229
WshShell.SendKeys "X"
Wscript.sleep 11
WshShell.SendKeys "E"
Wscript.sleep 13
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "X"
Wscript.sleep 481
WshShell.SendKeys "X"
Wscript.sleep 509
WshShell.SendKeys "X"
Wscript.sleep 8
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "F"
Wscript.sleep 482
WshShell.SendKeys "X"
Wscript.sleep 235
WshShell.SendKeys "C"
Wscript.sleep 216
WshShell.SendKeys "X"
Wscript.sleep 227
WshShell.SendKeys "Z"
Wscript.sleep 239
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 457
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "G"
Wscript.sleep 440
WshShell.SendKeys "G"
Wscript.sleep 14
WshShell.SendKeys "S"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 502
WshShell.SendKeys "G"
Wscript.sleep 223
WshShell.SendKeys "Z"
Wscript.sleep 260
WshShell.SendKeys "G"
Wscript.sleep 213
WshShell.SendKeys "F"
Wscript.sleep 230
WshShell.SendKeys "A"
Wscript.sleep 14
WshShell.SendKeys "R"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 432
WshShell.SendKeys "D"
Wscript.sleep 717
WshShell.SendKeys "S"
Wscript.sleep 191
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "W"
Wscript.sleep 6
WshShell.SendKeys "A"
Wscript.sleep 457
WshShell.SendKeys "S"
Wscript.sleep 439
WshShell.SendKeys "D"
Wscript.sleep 417
WshShell.SendKeys "F"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 7
WshShell.SendKeys "S"
Wscript.sleep 498
WshShell.SendKeys "F"
Wscript.sleep 226
WshShell.SendKeys "G"
Wscript.sleep 241
WshShell.SendKeys "F"
Wscript.sleep 236
WshShell.SendKeys "G"
Wscript.sleep 226
WshShell.SendKeys "A"
Wscript.sleep 9
WshShell.SendKeys "T"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 884
WshShell.SendKeys "G"
Wscript.sleep 215
WshShell.SendKeys "Z"
Wscript.sleep 237
WshShell.SendKeys "X"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 15
WshShell.SendKeys "Q"
Wscript.sleep 452
WshShell.SendKeys "X"
Wscript.sleep 445
WshShell.SendKeys "X"
Wscript.sleep 473
WshShell.SendKeys "F"
Wscript.sleep 14
WshShell.SendKeys "X"
Wscript.sleep 14
WshShell.SendKeys "T"
Wscript.sleep 488
WshShell.SendKeys "X"
Wscript.sleep 214
WshShell.SendKeys "C"
Wscript.sleep 221
WshShell.SendKeys "X"
Wscript.sleep 221
WshShell.SendKeys "Z"
Wscript.sleep 246
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 481
WshShell.SendKeys "G"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 425
WshShell.SendKeys "G"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 8
WshShell.SendKeys "S"
Wscript.sleep 472
WshShell.SendKeys "G"
Wscript.sleep 227
WshShell.SendKeys "Z"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 241
WshShell.SendKeys "D"
Wscript.sleep 7
WshShell.SendKeys "R"
Wscript.sleep 6
WshShell.SendKeys "A"
Wscript.sleep 483
WshShell.SendKeys "D"
Wscript.sleep 728
WshShell.SendKeys "S"
Wscript.sleep 214
WshShell.SendKeys "W"
Wscript.sleep 7
WshShell.SendKeys "R"
Wscript.sleep 18
WshShell.SendKeys "A"
Wscript.sleep 468
WshShell.SendKeys "S"
Wscript.sleep 487
WshShell.SendKeys "D"
Wscript.sleep 499
WshShell.SendKeys "S"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "F"
Wscript.sleep 483
WshShell.SendKeys "F"
Wscript.sleep 236
WshShell.SendKeys "G"
Wscript.sleep 226
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 219
WshShell.SendKeys "S"
Wscript.sleep 13
WshShell.SendKeys "T"
Wscript.sleep 11
WshShell.SendKeys "F"
Wscript.sleep 946
WshShell.SendKeys "D"
Wscript.sleep 232
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 6
WshShell.SendKeys "Q"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 258
WshShell.SendKeys "D"
Wscript.sleep 212
WshShell.SendKeys "X"
Wscript.sleep 685
WshShell.SendKeys "G"
Wscript.sleep 221
WshShell.SendKeys "S"
Wscript.sleep 18
WshShell.SendKeys "F"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 477
WshShell.SendKeys "X"
Wscript.sleep 706
WshShell.SendKeys "F"
Wscript.sleep 211
WshShell.SendKeys "G"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 21
WshShell.SendKeys "A"
Wscript.sleep 238
WshShell.SendKeys "A"
Wscript.sleep 220
WshShell.SendKeys "G"
Wscript.sleep 765
WshShell.SendKeys "D"
Wscript.sleep 220
WshShell.SendKeys "S"
Wscript.sleep 8
WshShell.SendKeys "T"
Wscript.sleep 11
WshShell.SendKeys "E"
Wscript.sleep 952
WshShell.SendKeys "T"
Wscript.sleep 464
WshShell.SendKeys "D"
Wscript.sleep 7
WshShell.SendKeys "R"
Wscript.sleep 14
WshShell.SendKeys "A"
Wscript.sleep 492
WshShell.SendKeys "S"
Wscript.sleep 638
WshShell.SendKeys "D"
Wscript.sleep 199
WshShell.SendKeys "F"
Wscript.sleep 233
WshShell.SendKeys "E"
Wscript.sleep 5
WshShell.SendKeys "T"
Wscript.sleep 486
WshShell.SendKeys "D"
Wscript.sleep 463
WshShell.SendKeys "F"
Wscript.sleep 234
WshShell.SendKeys "G"
Wscript.sleep 278
WshShell.SendKeys "F"
Wscript.sleep 15
WshShell.SendKeys "T"
Wscript.sleep 22
WshShell.SendKeys "Z"
Wscript.sleep 472
WshShell.SendKeys "Z"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 193
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 255
WshShell.SendKeys "A"
Wscript.sleep 24
WshShell.SendKeys "F"
Wscript.sleep 885
WshShell.SendKeys "D"
Wscript.sleep 446
WshShell.SendKeys "Q"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 1007
WshShell.SendKeys "D"
Wscript.sleep 452
WshShell.SendKeys "Q"
Wscript.sleep 13
WshShell.SendKeys "E"
Wscript.sleep 972
WshShell.SendKeys "D"
Wscript.sleep 498
WshShell.SendKeys "Q"
Wscript.sleep 12
WshShell.SendKeys "E"
Wscript.sleep 1024
WshShell.SendKeys "G"
Wscript.sleep 219
WshShell.SendKeys "Z"
Wscript.sleep 236
WshShell.SendKeys "X"
Wscript.sleep 8
WshShell.SendKeys "Q"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 468
WshShell.SendKeys "X"
Wscript.sleep 488
WshShell.SendKeys "X"
Wscript.sleep 18
WshShell.SendKeys "E"
Wscript.sleep 501
WshShell.SendKeys "F"
Wscript.sleep 6
WshShell.SendKeys "X"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "X"
Wscript.sleep 235
WshShell.SendKeys "C"
Wscript.sleep 220
WshShell.SendKeys "X"
Wscript.sleep 212
WshShell.SendKeys "Z"
Wscript.sleep 246
WshShell.SendKeys "D"
Wscript.sleep 7
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "G"
Wscript.sleep 466
WshShell.SendKeys "G"
Wscript.sleep 448
WshShell.SendKeys "G"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 452
WshShell.SendKeys "G"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 8
WshShell.SendKeys "S"
Wscript.sleep 490
WshShell.SendKeys "G"
Wscript.sleep 233
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 244
WshShell.SendKeys "D"
Wscript.sleep 8
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "R"
Wscript.sleep 437
WshShell.SendKeys "D"
Wscript.sleep 683
WshShell.SendKeys "S"
Wscript.sleep 220
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "W"
Wscript.sleep 4
WshShell.SendKeys "R"
Wscript.sleep 458
WshShell.SendKeys "S"
Wscript.sleep 473
WshShell.SendKeys "D"
Wscript.sleep 438
WshShell.SendKeys "S"
Wscript.sleep 31
WshShell.SendKeys "F"
Wscript.sleep 11
WshShell.SendKeys "T"
Wscript.sleep 473
WshShell.SendKeys "F"
Wscript.sleep 216
WshShell.SendKeys "G"
Wscript.sleep 237
WshShell.SendKeys "F"
Wscript.sleep 232
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 12
WshShell.SendKeys "T"
Wscript.sleep 19
WshShell.SendKeys "F"
Wscript.sleep 824
WshShell.SendKeys "G"
Wscript.sleep 202
WshShell.SendKeys "Z"
Wscript.sleep 222
WshShell.SendKeys "X"
Wscript.sleep 7
WshShell.SendKeys "Q"
Wscript.sleep 5
WshShell.SendKeys "E"
Wscript.sleep 470
WshShell.SendKeys "X"
Wscript.sleep 481
WshShell.SendKeys "X"
Wscript.sleep 15
WshShell.SendKeys "E"
Wscript.sleep 466
WshShell.SendKeys "X"
Wscript.sleep 16
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "F"
Wscript.sleep 478
WshShell.SendKeys "X"
Wscript.sleep 212
WshShell.SendKeys "C"
Wscript.sleep 230
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "Z"
Wscript.sleep 233
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 5
WshShell.SendKeys "G"
Wscript.sleep 458
WshShell.SendKeys "G"
Wscript.sleep 475
WshShell.SendKeys "D"
Wscript.sleep 6
WshShell.SendKeys "G"
Wscript.sleep 445
WshShell.SendKeys "G"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 9
WshShell.SendKeys "S"
Wscript.sleep 476
WshShell.SendKeys "G"
Wscript.sleep 227
WshShell.SendKeys "Z"
Wscript.sleep 216
WshShell.SendKeys "G"
Wscript.sleep 199
WshShell.SendKeys "F"
Wscript.sleep 223
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 471
WshShell.SendKeys "D"
Wscript.sleep 737
WshShell.SendKeys "S"
Wscript.sleep 243
WshShell.SendKeys "A"
Wscript.sleep 8
WshShell.SendKeys "W"
Wscript.sleep 5
WshShell.SendKeys "R"
Wscript.sleep 484
WshShell.SendKeys "S"
Wscript.sleep 809
WshShell.SendKeys "D"
Wscript.sleep 624
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "F"
Wscript.sleep 5
WshShell.SendKeys "T"
Wscript.sleep 632
WshShell.SendKeys "F"
Wscript.sleep 316
WshShell.SendKeys "G"
Wscript.sleep 381
WshShell.SendKeys "F"
Wscript.sleep 407
WshShell.SendKeys "G"
Wscript.sleep 464
WshShell.SendKeys "W"
Wscript.sleep 14
WshShell.SendKeys "F"
Wscript.sleep 7
WshShell.SendKeys "T"
