Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 187
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 748
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 748
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "Z"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 561
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "Z"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 561
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "Z"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 561
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "Z"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 187
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "Z"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "Z"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 748
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "C"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 561
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "C"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "C"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 561
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 374
WshShell.SendKeys "C"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 748
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 561
WshShell.SendKeys "C"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 748
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "Q"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 561
WshShell.SendKeys "C"
Wscript.sleep 187
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 561
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 187
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "Q"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 374
WshShell.SendKeys "S"
Wscript.sleep 748
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 187
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "G"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 187
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
Wscript.sleep 561
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 374
WshShell.SendKeys "T"
Wscript.sleep 187
WshShell.SendKeys "D"
Wscript.sleep 374
WshShell.SendKeys "F"
