Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 5379
WshShell.SendKeys "E"
Wscript.sleep 461
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 924
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "D"
Wscript.sleep 464
WshShell.SendKeys "F"
WshShell.SendKeys "T"
Wscript.sleep 924
WshShell.SendKeys "G"
Wscript.sleep 462
WshShell.SendKeys "X"
Wscript.sleep 463
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 924
WshShell.SendKeys "F"
Wscript.sleep 462
WshShell.SendKeys "D"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 924
WshShell.SendKeys "G"
Wscript.sleep 462
WshShell.SendKeys "F"
Wscript.sleep 464
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 924
WshShell.SendKeys "G"
Wscript.sleep 462
WshShell.SendKeys "F"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 924
WshShell.SendKeys "T"
Wscript.sleep 926
WshShell.SendKeys "E"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "S"
Wscript.sleep 462
WshShell.SendKeys "D"
Wscript.sleep 926
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "Q"
Wscript.sleep 463
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "D"
Wscript.sleep 463
WshShell.SendKeys "F"
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 461
WshShell.SendKeys "X"
Wscript.sleep 463
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 461
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "F"
WshShell.SendKeys "A"
Wscript.sleep 461
WshShell.SendKeys "D"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "W"
Wscript.sleep 464
WshShell.SendKeys "G"
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "F"
Wscript.sleep 464
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 461
WshShell.SendKeys "F"
Wscript.sleep 463
WshShell.SendKeys "A"
WshShell.SendKeys "E"
Wscript.sleep 461
WshShell.SendKeys "W"
Wscript.sleep 464
WshShell.SendKeys "T"
WshShell.SendKeys "E"
Wscript.sleep 926
WshShell.SendKeys "A"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "E"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "S"
Wscript.sleep 463
WshShell.SendKeys "D"
Wscript.sleep 926
WshShell.SendKeys "G"
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "R"
Wscript.sleep 464
WshShell.SendKeys "T"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 461
WshShell.SendKeys "W"
Wscript.sleep 463
WshShell.SendKeys "S"
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "A"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "T"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "E"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "E"
Wscript.sleep 2
WshShell.SendKeys "Q"
Wscript.sleep 460
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 461
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "R"
Wscript.sleep 463
WshShell.SendKeys "T"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "D"
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "S"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 461
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "E"
Wscript.sleep 924
WshShell.SendKeys "W"
Wscript.sleep 925
WshShell.SendKeys "Q"
Wscript.sleep 925
WshShell.SendKeys "E"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 462
WshShell.SendKeys "R"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 1387
WshShell.SendKeys "T"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "W"
Wscript.sleep 463
WshShell.SendKeys "S"
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "T"
WshShell.SendKeys "W"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "W"
Wscript.sleep 463
WshShell.SendKeys "E"
WshShell.SendKeys "Q"
Wscript.sleep 925
WshShell.SendKeys "E"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "W"
Wscript.sleep 464
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 925
WshShell.SendKeys "E"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 460
WshShell.SendKeys "W"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 461
WshShell.SendKeys "W"
Wscript.sleep 464
WshShell.SendKeys "T"
Wscript.sleep 924
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "S"
Wscript.sleep 462
WshShell.SendKeys "D"
Wscript.sleep 926
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 461
WshShell.SendKeys "X"
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "C"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 463
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 461
WshShell.SendKeys "C"
Wscript.sleep 1
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "V"
Wscript.sleep 1
WshShell.SendKeys "S"
Wscript.sleep 462
WshShell.SendKeys "X"
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "C"
WshShell.SendKeys "Q"
Wscript.sleep 463
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "F"
WshShell.SendKeys "E"
Wscript.sleep 462
WshShell.SendKeys "G"
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "T"
Wscript.sleep 464
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 461
WshShell.SendKeys "X"
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "C"
WshShell.SendKeys "Q"
Wscript.sleep 462
WshShell.SendKeys "R"
Wscript.sleep 463
WshShell.SendKeys "A"
Wscript.sleep 463
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 463
WshShell.SendKeys "C"
WshShell.SendKeys "W"
Wscript.sleep 463
WshShell.SendKeys "B"
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "V"
Wscript.sleep 1
WshShell.SendKeys "S"
Wscript.sleep 461
WshShell.SendKeys "X"
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "G"
WshShell.SendKeys "Q"
Wscript.sleep 463
WshShell.SendKeys "E"
Wscript.sleep 462
WshShell.SendKeys "B"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 461
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "V"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 460
WshShell.SendKeys "T"
Wscript.sleep 464
WshShell.SendKeys "G"
WshShell.SendKeys "S"
Wscript.sleep 463
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "C"
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "R"
Wscript.sleep 464
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "C"
WshShell.SendKeys "W"
Wscript.sleep 461
WshShell.SendKeys "T"
Wscript.sleep 464
WshShell.SendKeys "V"
WshShell.SendKeys "S"
Wscript.sleep 464
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "C"
WshShell.SendKeys "Q"
Wscript.sleep 461
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 462
WshShell.SendKeys "F"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 462
WshShell.SendKeys "G"
WshShell.SendKeys "W"
Wscript.sleep 462
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "S"
Wscript.sleep 462
WshShell.SendKeys "F"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 461
WshShell.SendKeys "A"
WshShell.SendKeys "Q"
Wscript.sleep 463
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "G"
WshShell.SendKeys "A"
Wscript.sleep 463
WshShell.SendKeys "F"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "A"
WshShell.SendKeys "W"
Wscript.sleep 925
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 925
WshShell.SendKeys "A"
Wscript.sleep 1
WshShell.SendKeys "Q"
Wscript.sleep 1847
WshShell.SendKeys "D"
Wscript.sleep 926
WshShell.SendKeys "G"
WshShell.SendKeys "T"
Wscript.sleep 462
WshShell.SendKeys "F"
Wscript.sleep 463
WshShell.SendKeys "A"
WshShell.SendKeys "R"
Wscript.sleep 461
WshShell.SendKeys "Q"
Wscript.sleep 463
WshShell.SendKeys "G"
WshShell.SendKeys "E"
Wscript.sleep 463
WshShell.SendKeys "F"
Wscript.sleep 463
WshShell.SendKeys "A"
WshShell.SendKeys "W"
Wscript.sleep 924
WshShell.SendKeys "T"
Wscript.sleep 926
WshShell.SendKeys "C"
Wscript.sleep 1
WshShell.SendKeys "Q"
