Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 500
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 600
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 600
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 600
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "W"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 600
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 600
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
WshShell.SendKeys "B"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "C"
WshShell.SendKeys "B"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "B"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
