Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "W"
Wscript.sleep 450
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 450
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 450
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "W"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 450
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 450
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 450
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 600
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 450
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "V"
