Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 960
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 480
WshShell.SendKeys "B"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 480
WshShell.SendKeys "B"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 480
WshShell.SendKeys "T"
WshShell.SendKeys "B"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "T"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 480
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "R"
Wscript.sleep 480
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 960
WshShell.SendKeys "D"
Wscript.sleep 960
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 960
WshShell.SendKeys "T"
Wscript.sleep 960
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "E"
Wscript.sleep 480
WshShell.SendKeys "A"
Wscript.sleep 480
WshShell.SendKeys "S"
Wscript.sleep 480
WshShell.SendKeys "D"
Wscript.sleep 480
WshShell.SendKeys "G"
Wscript.sleep 480
WshShell.SendKeys "X"
Wscript.sleep 480
WshShell.SendKeys "V"
Wscript.sleep 480
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
