Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 705
WshShell.SendKeys "G"
Wscript.sleep 12
WshShell.SendKeys "D"
Wscript.sleep 26
WshShell.SendKeys "A"
Wscript.sleep 1108
WshShell.SendKeys "F"
Wscript.sleep 201
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 35
WshShell.SendKeys "S"
Wscript.sleep 792
WshShell.SendKeys "E"
Wscript.sleep 775
WshShell.SendKeys "A"
Wscript.sleep 19
WshShell.SendKeys "Q"
Wscript.sleep 10
WshShell.SendKeys "R"
Wscript.sleep 1141
WshShell.SendKeys "T"
Wscript.sleep 218
WshShell.SendKeys "R"
Wscript.sleep 257
WshShell.SendKeys "E"
Wscript.sleep 56
WshShell.SendKeys "Q"
Wscript.sleep 782
WshShell.SendKeys "W"
Wscript.sleep 775
WshShell.SendKeys "A"
Wscript.sleep 21
WshShell.SendKeys "D"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 391
WshShell.SendKeys "F"
Wscript.sleep 405
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "B"
Wscript.sleep 391
WshShell.SendKeys "X"
Wscript.sleep 22
WshShell.SendKeys "V"
Wscript.sleep 3
WshShell.SendKeys "G"
Wscript.sleep 793
WshShell.SendKeys "G"
Wscript.sleep 821
WshShell.SendKeys "Z"
Wscript.sleep 14
WshShell.SendKeys "C"
Wscript.sleep 3
WshShell.SendKeys "D"
Wscript.sleep 1663
WshShell.SendKeys "V"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 11
WshShell.SendKeys "X"
Wscript.sleep 3146
WshShell.SendKeys "Q"
Wscript.sleep 13
WshShell.SendKeys "A"
Wscript.sleep 3
WshShell.SendKeys "E"
Wscript.sleep 766
WshShell.SendKeys "G"
Wscript.sleep 796
WshShell.SendKeys "E"
Wscript.sleep 4
WshShell.SendKeys "T"
Wscript.sleep 28
WshShell.SendKeys "S"
Wscript.sleep 1699
WshShell.SendKeys "Q"
Wscript.sleep 4
WshShell.SendKeys "R"
Wscript.sleep 10
WshShell.SendKeys "A"
Wscript.sleep 343
WshShell.SendKeys "S"
Wscript.sleep 393
WshShell.SendKeys "D"
Wscript.sleep 381
WshShell.SendKeys "F"
Wscript.sleep 418
WshShell.SendKeys "G"
Wscript.sleep 12
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "D"
Wscript.sleep 1594
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "Q"
Wscript.sleep 3
WshShell.SendKeys "R"
Wscript.sleep 790
WshShell.SendKeys "C"
Wscript.sleep 773
WshShell.SendKeys "F"
Wscript.sleep 13
WshShell.SendKeys "S"
Wscript.sleep 10
WshShell.SendKeys "X"
Wscript.sleep 367
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "X"
Wscript.sleep 585
WshShell.SendKeys "F"
Wscript.sleep 372
WshShell.SendKeys "G"
Wscript.sleep 13
WshShell.SendKeys "T"
Wscript.sleep 12
WshShell.SendKeys "D"
Wscript.sleep 734
WshShell.SendKeys "Q"
Wscript.sleep 423
WshShell.SendKeys "T"
Wscript.sleep 381
WshShell.SendKeys "D"
Wscript.sleep 401
WshShell.SendKeys "G"
Wscript.sleep 406
WshShell.SendKeys "X"
Wscript.sleep 809
WshShell.SendKeys "R"
Wscript.sleep 11
WshShell.SendKeys "A"
Wscript.sleep 4
WshShell.SendKeys "Q"
Wscript.sleep 799
WshShell.SendKeys "C"
Wscript.sleep 746
WshShell.SendKeys "F"
Wscript.sleep 14
WshShell.SendKeys "X"
Wscript.sleep 13
WshShell.SendKeys "S"
Wscript.sleep 359
WshShell.SendKeys "F"
Wscript.sleep 425
WshShell.SendKeys "G"
Wscript.sleep 382
WshShell.SendKeys "Z"
Wscript.sleep 392
WshShell.SendKeys "A"
Wscript.sleep 19
WshShell.SendKeys "D"
Wscript.sleep 3
WshShell.SendKeys "G"
Wscript.sleep 1250
WshShell.SendKeys "F"
Wscript.sleep 390
WshShell.SendKeys "A"
Wscript.sleep 28
WshShell.SendKeys "D"
Wscript.sleep 9
WshShell.SendKeys "E"
Wscript.sleep 755
WshShell.SendKeys "D"
Wscript.sleep 361
WshShell.SendKeys "S"
Wscript.sleep 387
WshShell.SendKeys "R"
Wscript.sleep 35
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "Q"
Wscript.sleep 796
WshShell.SendKeys "G"
Wscript.sleep 806
WshShell.SendKeys "S"
Wscript.sleep 5
WshShell.SendKeys "F"
Wscript.sleep 4
WshShell.SendKeys "T"
Wscript.sleep 1154
WshShell.SendKeys "S"
Wscript.sleep 410
WshShell.SendKeys "E"
Wscript.sleep 25
WshShell.SendKeys "A"
Wscript.sleep 6
WshShell.SendKeys "Q"
Wscript.sleep 1557
WshShell.SendKeys "Q"
Wscript.sleep 398
WshShell.SendKeys "E"
Wscript.sleep 358
WshShell.SendKeys "A"
Wscript.sleep 407
WshShell.SendKeys "S"
Wscript.sleep 399
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "Q"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 809
WshShell.SendKeys "G"
Wscript.sleep 831
WshShell.SendKeys "S"
Wscript.sleep 14
WshShell.SendKeys "E"
Wscript.sleep 4
WshShell.SendKeys "T"
Wscript.sleep 841
WshShell.SendKeys "E"
Wscript.sleep 874
WshShell.SendKeys "Q"
Wscript.sleep 10
WshShell.SendKeys "A"
Wscript.sleep 18
WshShell.SendKeys "R"
Wscript.sleep 785
WshShell.SendKeys "S"
Wscript.sleep 441
WshShell.SendKeys "D"
Wscript.sleep 416
WshShell.SendKeys "F"
Wscript.sleep 410
WshShell.SendKeys "D"
Wscript.sleep 4
WshShell.SendKeys "G"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 835
WshShell.SendKeys "T"
Wscript.sleep 391
WshShell.SendKeys "D"
Wscript.sleep 425
WshShell.SendKeys "G"
Wscript.sleep 389
WshShell.SendKeys "R"
Wscript.sleep 14
WshShell.SendKeys "Q"
Wscript.sleep 19
WshShell.SendKeys "A"
Wscript.sleep 810
WshShell.SendKeys "C"
Wscript.sleep 813
WshShell.SendKeys "X"
Wscript.sleep 4
WshShell.SendKeys "S"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 616
WshShell.SendKeys "C"
Wscript.sleep 217
WshShell.SendKeys "X"
Wscript.sleep 398
WshShell.SendKeys "F"
Wscript.sleep 392
WshShell.SendKeys "D"
Wscript.sleep 22
WshShell.SendKeys "G"
Wscript.sleep 4
WshShell.SendKeys "T"
Wscript.sleep 3367
WshShell.SendKeys "A"
Wscript.sleep 4
WshShell.SendKeys "Q"
Wscript.sleep 8
WshShell.SendKeys "R"
Wscript.sleep 761
WshShell.SendKeys "C"
Wscript.sleep 774
WshShell.SendKeys "F"
Wscript.sleep 39
WshShell.SendKeys "S"
Wscript.sleep 23
WshShell.SendKeys "X"
Wscript.sleep 369
WshShell.SendKeys "F"
Wscript.sleep 418
WshShell.SendKeys "G"
Wscript.sleep 390
WshShell.SendKeys "Z"
Wscript.sleep 415
WshShell.SendKeys "A"
Wscript.sleep 21
WshShell.SendKeys "D"
Wscript.sleep 9
WshShell.SendKeys "G"
Wscript.sleep 1244
WshShell.SendKeys "F"
Wscript.sleep 398
WshShell.SendKeys "D"
Wscript.sleep 4
WshShell.SendKeys "E"
Wscript.sleep 9
WshShell.SendKeys "A"
Wscript.sleep 786
WshShell.SendKeys "D"
Wscript.sleep 392
WshShell.SendKeys "S"
Wscript.sleep 373
WshShell.SendKeys "E"
Wscript.sleep 38
WshShell.SendKeys "A"
Wscript.sleep 7
WshShell.SendKeys "Q"
Wscript.sleep 761
WshShell.SendKeys "G"
Wscript.sleep 798
WshShell.SendKeys "T"
Wscript.sleep 21
WshShell.SendKeys "S"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 1184
WshShell.SendKeys "S"
Wscript.sleep 398
WshShell.SendKeys "E"
Wscript.sleep 22
WshShell.SendKeys "Q"
Wscript.sleep 4
WshShell.SendKeys "A"
Wscript.sleep 1621
WshShell.SendKeys "Q"
Wscript.sleep 390
WshShell.SendKeys "E"
Wscript.sleep 407
WshShell.SendKeys "A"
Wscript.sleep 367
WshShell.SendKeys "S"
Wscript.sleep 414
WshShell.SendKeys "A"
Wscript.sleep 14
WshShell.SendKeys "D"
Wscript.sleep 5
WshShell.SendKeys "E"
Wscript.sleep 357
WshShell.SendKeys "F"
Wscript.sleep 390
WshShell.SendKeys "G"
Wscript.sleep 356
WshShell.SendKeys "D"
Wscript.sleep 385
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 14
WshShell.SendKeys "S"
Wscript.sleep 803
WshShell.SendKeys "T"
Wscript.sleep 783
WshShell.SendKeys "Q"
Wscript.sleep 10
WshShell.SendKeys "A"
Wscript.sleep 12
WshShell.SendKeys "R"
Wscript.sleep 351
WshShell.SendKeys "D"
Wscript.sleep 407
WshShell.SendKeys "T"
Wscript.sleep 23
WshShell.SendKeys "S"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 373
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 825
WshShell.SendKeys "A"
Wscript.sleep 376
WshShell.SendKeys "S"
Wscript.sleep 358
WshShell.SendKeys "A"
Wscript.sleep 23
WshShell.SendKeys "D"
Wscript.sleep 4
WshShell.SendKeys "E"
Wscript.sleep 364
WshShell.SendKeys "F"
Wscript.sleep 390
WshShell.SendKeys "G"
Wscript.sleep 356
WshShell.SendKeys "D"
Wscript.sleep 382
WshShell.SendKeys "S"
Wscript.sleep 18
WshShell.SendKeys "E"
Wscript.sleep 5
WshShell.SendKeys "T"
Wscript.sleep 760
WshShell.SendKeys "T"
Wscript.sleep 772
WshShell.SendKeys "Q"
Wscript.sleep 6
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "A"
Wscript.sleep 362
WshShell.SendKeys "D"
Wscript.sleep 390
WshShell.SendKeys "T"
Wscript.sleep 13
WshShell.SendKeys "F"
Wscript.sleep 29
WshShell.SendKeys "S"
Wscript.sleep 351
WshShell.SendKeys "D"
Wscript.sleep 404
WshShell.SendKeys "T"
Wscript.sleep 24
WshShell.SendKeys "D"
Wscript.sleep 9
WshShell.SendKeys "E"
Wscript.sleep 934
WshShell.SendKeys "A"
Wscript.sleep 391
WshShell.SendKeys "S"
Wscript.sleep 360
WshShell.SendKeys "D"
Wscript.sleep 5
WshShell.SendKeys "E"
Wscript.sleep 8
WshShell.SendKeys "A"
Wscript.sleep 367
WshShell.SendKeys "F"
Wscript.sleep 402
WshShell.SendKeys "G"
Wscript.sleep 389
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
Wscript.sleep 12
WshShell.SendKeys "S"
Wscript.sleep 4
WshShell.SendKeys "E"
Wscript.sleep 798
WshShell.SendKeys "T"
Wscript.sleep 773
WshShell.SendKeys "Q"
Wscript.sleep 5
WshShell.SendKeys "A"
Wscript.sleep 33
WshShell.SendKeys "R"
Wscript.sleep 345
WshShell.SendKeys "D"
Wscript.sleep 424
WshShell.SendKeys "F"
Wscript.sleep 5
WshShell.SendKeys "T"
Wscript.sleep 19
WshShell.SendKeys "S"
Wscript.sleep 385
WshShell.SendKeys "D"
Wscript.sleep 389
WshShell.SendKeys "D"
Wscript.sleep 13
WshShell.SendKeys "G"
Wscript.sleep 12
WshShell.SendKeys "T"
Wscript.sleep 1178
WshShell.SendKeys "A"
Wscript.sleep 221
WshShell.SendKeys "S"
Wscript.sleep 289
WshShell.SendKeys "A"
Wscript.sleep 6
WshShell.SendKeys "D"
Wscript.sleep 4
WshShell.SendKeys "E"
Wscript.sleep 373
WshShell.SendKeys "F"
Wscript.sleep 415
WshShell.SendKeys "G"
Wscript.sleep 423
WshShell.SendKeys "D"
Wscript.sleep 362
WshShell.SendKeys "S"
Wscript.sleep 21
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 794
WshShell.SendKeys "T"
Wscript.sleep 856
WshShell.SendKeys "Q"
Wscript.sleep 5
WshShell.SendKeys "A"
Wscript.sleep 9
WshShell.SendKeys "R"
Wscript.sleep 429
WshShell.SendKeys "D"
Wscript.sleep 465
WshShell.SendKeys "F"
Wscript.sleep 4
WshShell.SendKeys "T"
Wscript.sleep 28
WshShell.SendKeys "S"
Wscript.sleep 407
WshShell.SendKeys "D"
Wscript.sleep 485
WshShell.SendKeys "Q"
Wscript.sleep 28
WshShell.SendKeys "E"
Wscript.sleep 4
WshShell.SendKeys "T"
Wscript.sleep 1778
WshShell.SendKeys "A"
Wscript.sleep 8
WshShell.SendKeys "D"
Wscript.sleep 4
WshShell.SendKeys "E"
Wscript.sleep 431
WshShell.SendKeys "F"
Wscript.sleep 464
WshShell.SendKeys "G"
Wscript.sleep 474
WshShell.SendKeys "D"
Wscript.sleep 509
WshShell.SendKeys "E"
Wscript.sleep 5
WshShell.SendKeys "T"
Wscript.sleep 16
WshShell.SendKeys "S"
Wscript.sleep 1052
WshShell.SendKeys "T"
Wscript.sleep 1016
WshShell.SendKeys "Q"
Wscript.sleep 11
WshShell.SendKeys "A"
Wscript.sleep 16
WshShell.SendKeys "R"
Wscript.sleep 497
WshShell.SendKeys "D"
Wscript.sleep 615
WshShell.SendKeys "S"
Wscript.sleep 5
WshShell.SendKeys "W"
Wscript.sleep 3
WshShell.SendKeys "T"
Wscript.sleep 565
WshShell.SendKeys "D"
Wscript.sleep 608
WshShell.SendKeys "D"
Wscript.sleep 12
WshShell.SendKeys "Q"
Wscript.sleep 5
WshShell.SendKeys "E"
Wscript.sleep 8
WshShell.SendKeys "T"
