Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 816
WshShell.SendKeys "D"
Wscript.sleep 816
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 544
WshShell.SendKeys "D"
Wscript.sleep 544
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "X"
Wscript.sleep 408
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "G"
Wscript.sleep 1088
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 816
WshShell.SendKeys "X"
Wscript.sleep 816
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 544
WshShell.SendKeys "F"
Wscript.sleep 544
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 408
WshShell.SendKeys "X"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "X"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 680
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 1632
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 408
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 816
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 544
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 680
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 816
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "A"
Wscript.sleep 816
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 816
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 816
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "A"
Wscript.sleep 408
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 408
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 816
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 544
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 816
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 816
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "A"
Wscript.sleep 816
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 816
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 816
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Z"
Wscript.sleep 816
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 816
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 544
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 408
WshShell.SendKeys "A"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 1360
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "S"
Wscript.sleep 544
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Z"
Wscript.sleep 408
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 816
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 544
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 544
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "D"
Wscript.sleep 544
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 272
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 680
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 408
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
