Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 400
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "C"
Wscript.sleep 1200
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 600
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 75
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "C"
Wscript.sleep 1200
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 600
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "C"
Wscript.sleep 675
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "F"
WshShell.SendKeys "C"
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
WshShell.SendKeys "C"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "C"
