Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 1568
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 392
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 392
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "Z"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "B"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "C"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "R"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 196
WshShell.SendKeys "Q"
Wscript.sleep 196
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "T"
Wscript.sleep 196
WshShell.SendKeys "W"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "C"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "E"
Wscript.sleep 98
WshShell.SendKeys "A"
Wscript.sleep 98
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "D"
Wscript.sleep 196
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "S"
Wscript.sleep 196
WshShell.SendKeys "A"
Wscript.sleep 196
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 196
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 196
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 784
WshShell.SendKeys "C"
WshShell.SendKeys "B"
