Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 560
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 560
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 336
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 560
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 560
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 336
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 560
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 560
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "Q"
Wscript.sleep 112
WshShell.SendKeys "W"
Wscript.sleep 336
WshShell.SendKeys "D"
Wscript.sleep 448
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 336
WshShell.SendKeys "E"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "C"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 560
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 112
WshShell.SendKeys "X"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "R"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "V"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 112
WshShell.SendKeys "C"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 112
WshShell.SendKeys "X"
Wscript.sleep 112
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "Q"
Wscript.sleep 224
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 112
WshShell.SendKeys "V"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 672
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 336
WshShell.SendKeys "W"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 336
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 336
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 336
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 224
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 448
WshShell.SendKeys "W"
Wscript.sleep 448
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "Q"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 336
WshShell.SendKeys "W"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 224
WshShell.SendKeys "W"
Wscript.sleep 112
WshShell.SendKeys "R"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "S"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "T"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 784
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 448
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 112
WshShell.SendKeys "D"
Wscript.sleep 112
WshShell.SendKeys "F"
Wscript.sleep 112
WshShell.SendKeys "G"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 224
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
Wscript.sleep 112
WshShell.SendKeys "T"
Wscript.sleep 112
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 224
WshShell.SendKeys "E"
WshShell.SendKeys "A"
