Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 1181
WshShell.SendKeys "Q"
Wscript.sleep 33
WshShell.SendKeys "T"
Wscript.sleep 2
WshShell.SendKeys "E"
Wscript.sleep 411
WshShell.SendKeys "G"
Wscript.sleep 463
WshShell.SendKeys "F"
Wscript.sleep 434
WshShell.SendKeys "D"
Wscript.sleep 421
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 914
WshShell.SendKeys "T"
Wscript.sleep 207
WshShell.SendKeys "T"
Wscript.sleep 227
WshShell.SendKeys "T"
Wscript.sleep 19
WshShell.SendKeys "Q"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 462
WshShell.SendKeys "G"
Wscript.sleep 415
WshShell.SendKeys "F"
Wscript.sleep 451
WshShell.SendKeys "D"
Wscript.sleep 347
WshShell.SendKeys "Q"
Wscript.sleep 49
WshShell.SendKeys "A"
Wscript.sleep 26
WshShell.SendKeys "R"
Wscript.sleep 1280
WshShell.SendKeys "A"
Wscript.sleep 46
WshShell.SendKeys "Q"
Wscript.sleep 4
WshShell.SendKeys "R"
Wscript.sleep 412
WshShell.SendKeys "Z"
Wscript.sleep 453
WshShell.SendKeys "G"
Wscript.sleep 485
WshShell.SendKeys "F"
Wscript.sleep 386
WshShell.SendKeys "S"
Wscript.sleep 2
WshShell.SendKeys "T"
Wscript.sleep 41
WshShell.SendKeys "W"
Wscript.sleep 1070
WshShell.SendKeys "X"
Wscript.sleep 70
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 358
WshShell.SendKeys "X"
Wscript.sleep 400
WshShell.SendKeys "Z"
Wscript.sleep 406
WshShell.SendKeys "F"
Wscript.sleep 388
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 1217
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 32
WshShell.SendKeys "Q"
Wscript.sleep 406
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 372
WshShell.SendKeys "Q"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 2
WshShell.SendKeys "E"
Wscript.sleep 725
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "E"
Wscript.sleep 21
WshShell.SendKeys "Q"
Wscript.sleep 429
WshShell.SendKeys "G"
Wscript.sleep 384
WshShell.SendKeys "F"
Wscript.sleep 419
WshShell.SendKeys "D"
Wscript.sleep 346
WshShell.SendKeys "R"
Wscript.sleep 39
WshShell.SendKeys "A"
Wscript.sleep 10
WshShell.SendKeys "Q"
Wscript.sleep 1075
WshShell.SendKeys "Q"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 34
WshShell.SendKeys "R"
Wscript.sleep 341
WshShell.SendKeys "Z"
Wscript.sleep 435
WshShell.SendKeys "G"
Wscript.sleep 419
WshShell.SendKeys "F"
Wscript.sleep 355
WshShell.SendKeys "X"
Wscript.sleep 1
WshShell.SendKeys "S"
Wscript.sleep 3
WshShell.SendKeys "F"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 386
WshShell.SendKeys "X"
Wscript.sleep 387
WshShell.SendKeys "X"
Wscript.sleep 367
WshShell.SendKeys "X"
Wscript.sleep 392
WshShell.SendKeys "F"
Wscript.sleep 2
WshShell.SendKeys "C"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 401
WshShell.SendKeys "X"
Wscript.sleep 454
WshShell.SendKeys "Z"
Wscript.sleep 401
WshShell.SendKeys "F"
Wscript.sleep 416
WshShell.SendKeys "Q"
Wscript.sleep 41
WshShell.SendKeys "E"
Wscript.sleep 8
WshShell.SendKeys "D"
Wscript.sleep 2
WshShell.SendKeys "T"
Wscript.sleep 598
WshShell.SendKeys "X"
Wscript.sleep 608
WshShell.SendKeys "Q"
Wscript.sleep 3
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "T"
Wscript.sleep 24
WshShell.SendKeys "E"
Wscript.sleep 310
WshShell.SendKeys "G"
Wscript.sleep 367
WshShell.SendKeys "G"
Wscript.sleep 575
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "G"
Wscript.sleep 44
WshShell.SendKeys "Q"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 313
WshShell.SendKeys "G"
Wscript.sleep 383
WshShell.SendKeys "G"
Wscript.sleep 521
WshShell.SendKeys "G"
Wscript.sleep 51
WshShell.SendKeys "Q"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 361
WshShell.SendKeys "X"
Wscript.sleep 385
WshShell.SendKeys "D"
Wscript.sleep 469
WshShell.SendKeys "F"
Wscript.sleep 154
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 31
WshShell.SendKeys "T"
Wscript.sleep 962
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "R"
Wscript.sleep 1
WshShell.SendKeys "Z"
Wscript.sleep 1
WshShell.SendKeys "A"
Wscript.sleep 271
WshShell.SendKeys "Z"
Wscript.sleep 385
WshShell.SendKeys "Z"
Wscript.sleep 486
WshShell.SendKeys "Z"
Wscript.sleep 121
WshShell.SendKeys "Z"
Wscript.sleep 1
WshShell.SendKeys "D"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 444
WshShell.SendKeys "G"
Wscript.sleep 414
WshShell.SendKeys "G"
Wscript.sleep 416
WshShell.SendKeys "G"
Wscript.sleep 120
WshShell.SendKeys "G"
Wscript.sleep 171
WshShell.SendKeys "E"
Wscript.sleep 34
WshShell.SendKeys "G"
Wscript.sleep 15
WshShell.SendKeys "T"
Wscript.sleep 443
WshShell.SendKeys "F"
Wscript.sleep 386
WshShell.SendKeys "F"
Wscript.sleep 380
WshShell.SendKeys "G"
Wscript.sleep 403
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "F"
Wscript.sleep 37
WshShell.SendKeys "W"
Wscript.sleep 697
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "G"
Wscript.sleep 48
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 341
WshShell.SendKeys "G"
Wscript.sleep 367
WshShell.SendKeys "G"
Wscript.sleep 607
WshShell.SendKeys "G"
Wscript.sleep 3
WshShell.SendKeys "E"
Wscript.sleep 42
WshShell.SendKeys "T"
Wscript.sleep 298
WshShell.SendKeys "G"
Wscript.sleep 366
WshShell.SendKeys "G"
Wscript.sleep 554
WshShell.SendKeys "G"
Wscript.sleep 42
WshShell.SendKeys "T"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 361
WshShell.SendKeys "X"
Wscript.sleep 360
WshShell.SendKeys "D"
Wscript.sleep 454
WshShell.SendKeys "F"
Wscript.sleep 166
WshShell.SendKeys "T"
Wscript.sleep 43
WshShell.SendKeys "G"
Wscript.sleep 1
WshShell.SendKeys "E"
Wscript.sleep 1022
WshShell.SendKeys "D"
Wscript.sleep 52
WshShell.SendKeys "R"
Wscript.sleep 7
WshShell.SendKeys "Z"
Wscript.sleep 11
WshShell.SendKeys "A"
Wscript.sleep 348
WshShell.SendKeys "Z"
Wscript.sleep 347
WshShell.SendKeys "Z"
Wscript.sleep 449
WshShell.SendKeys "Z"
Wscript.sleep 194
WshShell.SendKeys "Z"
Wscript.sleep 2
WshShell.SendKeys "D"
Wscript.sleep 1
WshShell.SendKeys "R"
Wscript.sleep 386
WshShell.SendKeys "G"
Wscript.sleep 367
WshShell.SendKeys "G"
Wscript.sleep 349
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 40
WshShell.SendKeys "X"
WshShell.SendKeys "S"
Wscript.sleep 1
WshShell.SendKeys "F"
Wscript.sleep 376
WshShell.SendKeys "X"
Wscript.sleep 404
WshShell.SendKeys "Z"
Wscript.sleep 392
WshShell.SendKeys "F"
Wscript.sleep 356
WshShell.SendKeys "Q"
Wscript.sleep 45
WshShell.SendKeys "E"
Wscript.sleep 2
WshShell.SendKeys "T"
Wscript.sleep 23
WshShell.SendKeys "D"
