Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "B"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "Q"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "Q"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Q"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 468
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 468
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "Q"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 156
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "Q"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "W"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "B"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 156
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "E"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "B"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "B"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 312
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 156
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "T"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "A"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "B"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 312
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 312
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "S"
Wscript.sleep 156
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "Z"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "B"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 156
WshShell.SendKeys "V"
Wscript.sleep 156
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 312
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 156
WshShell.SendKeys "G"
Wscript.sleep 156
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 312
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 156
WshShell.SendKeys "D"
Wscript.sleep 156
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 624
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 624
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 312
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 312
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
