Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 360
WshShell.SendKeys "T"
Wscript.sleep 256
WshShell.SendKeys "D"
Wscript.sleep 253
WshShell.SendKeys "F"
Wscript.sleep 264
WshShell.SendKeys "E"
Wscript.sleep 7
WshShell.SendKeys "F"
Wscript.sleep 7
WshShell.SendKeys "Q"
Wscript.sleep 542
WshShell.SendKeys "G"
Wscript.sleep 558
WshShell.SendKeys "G"
Wscript.sleep 1876
WshShell.SendKeys "D"
Wscript.sleep 287
WshShell.SendKeys "F"
Wscript.sleep 237
WshShell.SendKeys "G"
Wscript.sleep 283
WshShell.SendKeys "S"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 509
WshShell.SendKeys "X"
Wscript.sleep 563
WshShell.SendKeys "X"
Wscript.sleep 1599
WshShell.SendKeys "X"
Wscript.sleep 299
WshShell.SendKeys "C"
Wscript.sleep 275
WshShell.SendKeys "V"
Wscript.sleep 247
WshShell.SendKeys "A"
Wscript.sleep 35
WshShell.SendKeys "G"
Wscript.sleep 4
WshShell.SendKeys "V"
Wscript.sleep 577
WshShell.SendKeys "B"
Wscript.sleep 519
WshShell.SendKeys "B"
Wscript.sleep 1439
WshShell.SendKeys "F"
Wscript.sleep 572
WshShell.SendKeys "G"
Wscript.sleep 340
WshShell.SendKeys "F"
Wscript.sleep 298
WshShell.SendKeys "D"
Wscript.sleep 311
WshShell.SendKeys "E"
Wscript.sleep 7
WshShell.SendKeys "T"
Wscript.sleep 5
WshShell.SendKeys "S"
Wscript.sleep 1690
WshShell.SendKeys "B"
Wscript.sleep 448
WshShell.SendKeys "V"
Wscript.sleep 478
WshShell.SendKeys "X"
Wscript.sleep 487
WshShell.SendKeys "X"
Wscript.sleep 5
WshShell.SendKeys "R"
Wscript.sleep 17
WshShell.SendKeys "D"
Wscript.sleep 546
WshShell.SendKeys "C"
Wscript.sleep 488
WshShell.SendKeys "C"
Wscript.sleep 1709
WshShell.SendKeys "X"
Wscript.sleep 233
WshShell.SendKeys "Z"
Wscript.sleep 242
WshShell.SendKeys "E"
Wscript.sleep 7
WshShell.SendKeys "S"
Wscript.sleep 5
WshShell.SendKeys "Z"
Wscript.sleep 477
WshShell.SendKeys "X"
Wscript.sleep 478
WshShell.SendKeys "X"
Wscript.sleep 876
WshShell.SendKeys "D"
Wscript.sleep 6
WshShell.SendKeys "A"
Wscript.sleep 491
WshShell.SendKeys "D"
Wscript.sleep 496
WshShell.SendKeys "F"
Wscript.sleep 495
WshShell.SendKeys "G"
Wscript.sleep 475
WshShell.SendKeys "W"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 5
WshShell.SendKeys "R"
Wscript.sleep 484
WshShell.SendKeys "Z"
Wscript.sleep 838
WshShell.SendKeys "Z"
Wscript.sleep 461
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "W"
Wscript.sleep 821
WshShell.SendKeys "X"
Wscript.sleep 442
WshShell.SendKeys "Z"
Wscript.sleep 455
WshShell.SendKeys "W"
Wscript.sleep 22
WshShell.SendKeys "T"
Wscript.sleep 4
WshShell.SendKeys "G"
Wscript.sleep 1687
WshShell.SendKeys "T"
Wscript.sleep 8
WshShell.SendKeys "S"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 432
WshShell.SendKeys "T"
Wscript.sleep 441
WshShell.SendKeys "D"
Wscript.sleep 450
WshShell.SendKeys "F"
Wscript.sleep 404
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "F"
Wscript.sleep 9
WshShell.SendKeys "Q"
Wscript.sleep 482
WshShell.SendKeys "G"
Wscript.sleep 507
WshShell.SendKeys "G"
Wscript.sleep 1346
WshShell.SendKeys "E"
Wscript.sleep 7
WshShell.SendKeys "Q"
Wscript.sleep 1169
WshShell.SendKeys "D"
Wscript.sleep 295
WshShell.SendKeys "F"
Wscript.sleep 255
WshShell.SendKeys "G"
Wscript.sleep 298
WshShell.SendKeys "S"
Wscript.sleep 20
WshShell.SendKeys "E"
Wscript.sleep 13
WshShell.SendKeys "F"
Wscript.sleep 509
WshShell.SendKeys "X"
Wscript.sleep 493
WshShell.SendKeys "X"
Wscript.sleep 766
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "S"
Wscript.sleep 1132
WshShell.SendKeys "X"
Wscript.sleep 310
WshShell.SendKeys "C"
Wscript.sleep 332
WshShell.SendKeys "V"
Wscript.sleep 307
WshShell.SendKeys "V"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 13
WshShell.SendKeys "A"
Wscript.sleep 639
WshShell.SendKeys "B"
Wscript.sleep 606
WshShell.SendKeys "B"
Wscript.sleep 1017
WshShell.SendKeys "A"
Wscript.sleep 25
WshShell.SendKeys "G"
Wscript.sleep 620
WshShell.SendKeys "F"
Wscript.sleep 601
WshShell.SendKeys "G"
Wscript.sleep 358
WshShell.SendKeys "F"
Wscript.sleep 335
WshShell.SendKeys "D"
Wscript.sleep 342
WshShell.SendKeys "T"
Wscript.sleep 9
WshShell.SendKeys "E"
Wscript.sleep 11
WshShell.SendKeys "S"
Wscript.sleep 1688
WshShell.SendKeys "T"
Wscript.sleep 9
WshShell.SendKeys "E"
Wscript.sleep 535
WshShell.SendKeys "B"
Wscript.sleep 497
WshShell.SendKeys "V"
Wscript.sleep 435
WshShell.SendKeys "X"
Wscript.sleep 514
WshShell.SendKeys "X"
Wscript.sleep 7
WshShell.SendKeys "R"
Wscript.sleep 7
WshShell.SendKeys "D"
Wscript.sleep 513
WshShell.SendKeys "C"
Wscript.sleep 536
WshShell.SendKeys "C"
Wscript.sleep 917
WshShell.SendKeys "R"
Wscript.sleep 6
WshShell.SendKeys "D"
Wscript.sleep 1485
WshShell.SendKeys "X"
Wscript.sleep 243
WshShell.SendKeys "Z"
Wscript.sleep 235
WshShell.SendKeys "S"
Wscript.sleep 13
WshShell.SendKeys "E"
Wscript.sleep 5
WshShell.SendKeys "Z"
Wscript.sleep 513
WshShell.SendKeys "X"
Wscript.sleep 457
WshShell.SendKeys "X"
Wscript.sleep 834
WshShell.SendKeys "D"
Wscript.sleep 24
WshShell.SendKeys "A"
Wscript.sleep 489
WshShell.SendKeys "D"
Wscript.sleep 495
WshShell.SendKeys "F"
Wscript.sleep 529
WshShell.SendKeys "G"
Wscript.sleep 475
WshShell.SendKeys "W"
Wscript.sleep 22
WshShell.SendKeys "G"
Wscript.sleep 14
WshShell.SendKeys "R"
Wscript.sleep 589
WshShell.SendKeys "Z"
Wscript.sleep 998
WshShell.SendKeys "A"
Wscript.sleep 436
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "A"
Wscript.sleep 4
WshShell.SendKeys "D"
Wscript.sleep 973
WshShell.SendKeys "S"
Wscript.sleep 764
WshShell.SendKeys "Q"
Wscript.sleep 84
WshShell.SendKeys "E"
Wscript.sleep 38
WshShell.SendKeys "D"
Wscript.sleep 2006
WshShell.SendKeys "Q"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 453
WshShell.SendKeys "D"
Wscript.sleep 478
WshShell.SendKeys "G"
Wscript.sleep 473
WshShell.SendKeys "X"
Wscript.sleep 499
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "D"
Wscript.sleep 6
WshShell.SendKeys "C"
Wscript.sleep 1769
WshShell.SendKeys "D"
Wscript.sleep 13
WshShell.SendKeys "R"
Wscript.sleep 470
WshShell.SendKeys "S"
Wscript.sleep 462
WshShell.SendKeys "D"
Wscript.sleep 469
WshShell.SendKeys "C"
Wscript.sleep 513
WshShell.SendKeys "E"
Wscript.sleep 10
WshShell.SendKeys "S"
Wscript.sleep 5
WshShell.SendKeys "X"
Wscript.sleep 1676
WshShell.SendKeys "A"
Wscript.sleep 13
WshShell.SendKeys "D"
Wscript.sleep 496
WshShell.SendKeys "S"
Wscript.sleep 438
WshShell.SendKeys "D"
Wscript.sleep 477
WshShell.SendKeys "X"
Wscript.sleep 370
WshShell.SendKeys "X"
Wscript.sleep 42
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 433
WshShell.SendKeys "Z"
Wscript.sleep 425
WshShell.SendKeys "Z"
Wscript.sleep 467
WshShell.SendKeys "G"
Wscript.sleep 353
WshShell.SendKeys "W"
Wscript.sleep 21
WshShell.SendKeys "T"
Wscript.sleep 12
WshShell.SendKeys "G"
Wscript.sleep 415
WshShell.SendKeys "F"
Wscript.sleep 426
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 388
WshShell.SendKeys "F"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 5
WshShell.SendKeys "Q"
Wscript.sleep 428
WshShell.SendKeys "G"
Wscript.sleep 382
WshShell.SendKeys "G"
Wscript.sleep 689
WshShell.SendKeys "W"
Wscript.sleep 17
WshShell.SendKeys "R"
Wscript.sleep 664
WshShell.SendKeys "T"
Wscript.sleep 5
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "D"
Wscript.sleep 286
WshShell.SendKeys "G"
Wscript.sleep 290
WshShell.SendKeys "X"
Wscript.sleep 347
WshShell.SendKeys "R"
Wscript.sleep 6
WshShell.SendKeys "C"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 1276
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 867
WshShell.SendKeys "V"
Wscript.sleep 452
WshShell.SendKeys "V"
Wscript.sleep 453
WshShell.SendKeys "C"
Wscript.sleep 461
WshShell.SendKeys "E"
Wscript.sleep 8
WshShell.SendKeys "X"
Wscript.sleep 4
WshShell.SendKeys "S"
Wscript.sleep 1113
WshShell.SendKeys "G"
Wscript.sleep 278
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "X"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 514
WshShell.SendKeys "Z"
Wscript.sleep 765
WshShell.SendKeys "G"
Wscript.sleep 436
WshShell.SendKeys "W"
Wscript.sleep 26
WshShell.SendKeys "R"
Wscript.sleep 6
WshShell.SendKeys "G"
Wscript.sleep 466
WshShell.SendKeys "Z"
Wscript.sleep 736
WshShell.SendKeys "A"
Wscript.sleep 395
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "W"
Wscript.sleep 832
WshShell.SendKeys "S"
Wscript.sleep 438
WshShell.SendKeys "D"
Wscript.sleep 418
WshShell.SendKeys "W"
Wscript.sleep 21
WshShell.SendKeys "T"
Wscript.sleep 6
WshShell.SendKeys "G"
Wscript.sleep 1641
WshShell.SendKeys "T"
Wscript.sleep 15
WshShell.SendKeys "F"
Wscript.sleep 6
WshShell.SendKeys "S"
Wscript.sleep 415
WshShell.SendKeys "T"
Wscript.sleep 444
WshShell.SendKeys "D"
Wscript.sleep 385
WshShell.SendKeys "F"
Wscript.sleep 409
WshShell.SendKeys "Q"
Wscript.sleep 6
WshShell.SendKeys "E"
Wscript.sleep 4
WshShell.SendKeys "F"
Wscript.sleep 441
WshShell.SendKeys "G"
Wscript.sleep 435
WshShell.SendKeys "G"
Wscript.sleep 779
WshShell.SendKeys "Q"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 1187
WshShell.SendKeys "D"
Wscript.sleep 275
WshShell.SendKeys "F"
Wscript.sleep 254
WshShell.SendKeys "G"
Wscript.sleep 307
WshShell.SendKeys "E"
Wscript.sleep 10
WshShell.SendKeys "F"
Wscript.sleep 5
WshShell.SendKeys "S"
Wscript.sleep 577
WshShell.SendKeys "X"
Wscript.sleep 542
WshShell.SendKeys "X"
Wscript.sleep 894
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "S"
Wscript.sleep 1108
WshShell.SendKeys "X"
Wscript.sleep 303
WshShell.SendKeys "C"
Wscript.sleep 324
WshShell.SendKeys "V"
Wscript.sleep 265
WshShell.SendKeys "G"
Wscript.sleep 11
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "V"
Wscript.sleep 510
WshShell.SendKeys "B"
Wscript.sleep 467
WshShell.SendKeys "B"
Wscript.sleep 923
WshShell.SendKeys "A"
Wscript.sleep 5
WshShell.SendKeys "G"
Wscript.sleep 603
WshShell.SendKeys "F"
Wscript.sleep 500
WshShell.SendKeys "G"
Wscript.sleep 327
WshShell.SendKeys "F"
Wscript.sleep 341
WshShell.SendKeys "D"
Wscript.sleep 340
WshShell.SendKeys "E"
Wscript.sleep 6
WshShell.SendKeys "T"
Wscript.sleep 4
WshShell.SendKeys "S"
Wscript.sleep 1768
WshShell.SendKeys "T"
Wscript.sleep 7
WshShell.SendKeys "E"
Wscript.sleep 503
WshShell.SendKeys "B"
Wscript.sleep 434
WshShell.SendKeys "V"
Wscript.sleep 485
WshShell.SendKeys "X"
Wscript.sleep 431
WshShell.SendKeys "X"
Wscript.sleep 29
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 448
WshShell.SendKeys "C"
Wscript.sleep 453
WshShell.SendKeys "C"
Wscript.sleep 769
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 1136
WshShell.SendKeys "X"
Wscript.sleep 192
WshShell.SendKeys "Z"
Wscript.sleep 232
WshShell.SendKeys "Z"
Wscript.sleep 19
WshShell.SendKeys "E"
Wscript.sleep 4
WshShell.SendKeys "S"
Wscript.sleep 471
WshShell.SendKeys "X"
Wscript.sleep 426
WshShell.SendKeys "X"
Wscript.sleep 836
WshShell.SendKeys "A"
Wscript.sleep 8
WshShell.SendKeys "D"
Wscript.sleep 512
WshShell.SendKeys "D"
Wscript.sleep 465
WshShell.SendKeys "F"
Wscript.sleep 495
WshShell.SendKeys "G"
Wscript.sleep 405
WshShell.SendKeys "W"
Wscript.sleep 34
WshShell.SendKeys "R"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 459
WshShell.SendKeys "Z"
Wscript.sleep 796
WshShell.SendKeys "A"
Wscript.sleep 466
WshShell.SendKeys "A"
Wscript.sleep 44
WshShell.SendKeys "R"
Wscript.sleep 5
WshShell.SendKeys "D"
Wscript.sleep 921
WshShell.SendKeys "S"
Wscript.sleep 713
WshShell.SendKeys "Q"
Wscript.sleep 146
WshShell.SendKeys "E"
Wscript.sleep 160
WshShell.SendKeys "D"
Wscript.sleep 1608
WshShell.SendKeys "Q"
Wscript.sleep 9
WshShell.SendKeys "E"
Wscript.sleep 495
WshShell.SendKeys "D"
Wscript.sleep 433
WshShell.SendKeys "F"
Wscript.sleep 458
WshShell.SendKeys "G"
Wscript.sleep 433
WshShell.SendKeys "W"
Wscript.sleep 25
WshShell.SendKeys "R"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 404
WshShell.SendKeys "Z"
Wscript.sleep 852
WshShell.SendKeys "A"
Wscript.sleep 424
WshShell.SendKeys "A"
Wscript.sleep 30
WshShell.SendKeys "D"
Wscript.sleep 12
WshShell.SendKeys "R"
Wscript.sleep 997
WshShell.SendKeys "S"
Wscript.sleep 695
WshShell.SendKeys "Q"
Wscript.sleep 122
WshShell.SendKeys "E"
Wscript.sleep 97
WshShell.SendKeys "D"
Wscript.sleep 1758
WshShell.SendKeys "Q"
Wscript.sleep 25
WshShell.SendKeys "E"
Wscript.sleep 579
WshShell.SendKeys "D"
Wscript.sleep 570
WshShell.SendKeys "F"
Wscript.sleep 667
WshShell.SendKeys "G"
Wscript.sleep 661
WshShell.SendKeys "W"
Wscript.sleep 7
WshShell.SendKeys "G"
Wscript.sleep 4
WshShell.SendKeys "R"
Wscript.sleep 671
WshShell.SendKeys "Z"
Wscript.sleep 1132
WshShell.SendKeys "A"
Wscript.sleep 526
WshShell.SendKeys "A"
Wscript.sleep 47
WshShell.SendKeys "D"
Wscript.sleep 5
WshShell.SendKeys "R"
Wscript.sleep 1325
WshShell.SendKeys "S"
Wscript.sleep 786
WshShell.SendKeys "Q"
Wscript.sleep 64
WshShell.SendKeys "E"
Wscript.sleep 199
WshShell.SendKeys "D"
Wscript.sleep 1383
WshShell.SendKeys "G"
Wscript.sleep 323
WshShell.SendKeys "X"
Wscript.sleep 511
WshShell.SendKeys "X"
Wscript.sleep 142
WshShell.SendKeys "B"
