Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 1200
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 600
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 975
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 825
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 750
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 750
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 750
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 1425
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 525
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 525
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 75
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 525
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 525
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 750
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 75
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 525
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 525
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 75
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 525
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 525
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 750
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 825
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 1500
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 750
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 1500
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 750
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 1050
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 675
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 750
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 750
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 750
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 750
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 750
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 525
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
WshShell.SendKeys "V"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 525
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "X"
WshShell.SendKeys "X"
