Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 250
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 625
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 125
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "S"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 125
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 500
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 125
WshShell.SendKeys "D"
Wscript.sleep 125
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 250
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 250
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 250
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 250
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
