Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 400
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 504
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 504
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 756
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "B"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 756
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 252
WshShell.SendKeys "B"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "C"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 756
WshShell.SendKeys "G"
Wscript.sleep 504
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "F"
Wscript.sleep 378
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "F"
Wscript.sleep 126
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 378
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 126
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 378
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 126
WshShell.SendKeys "F"
Wscript.sleep 126
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 126
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 126
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 126
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 756
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "A"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 252
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "T"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 252
WshShell.SendKeys "T"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 756
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 1134
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 504
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 504
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 756
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "F"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 756
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "B"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 756
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 252
WshShell.SendKeys "B"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "C"
Wscript.sleep 252
WshShell.SendKeys "X"
Wscript.sleep 504
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 504
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 504
WshShell.SendKeys "X"
Wscript.sleep 252
WshShell.SendKeys "G"
Wscript.sleep 630
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 252
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 252
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
