Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 856
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 912
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 684
WshShell.SendKeys "D"
Wscript.sleep 114
WshShell.SendKeys "F"
Wscript.sleep 114
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 456
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 912
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 912
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "B"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Z"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 1140
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Z"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "R"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 1140
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "D"
Wscript.sleep 399
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "F"
Wscript.sleep 399
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "S"
Wscript.sleep 399
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 57
WshShell.SendKeys "E"
Wscript.sleep 399
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "A"
Wscript.sleep 399
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "F"
Wscript.sleep 399
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 684
WshShell.SendKeys "D"
Wscript.sleep 114
WshShell.SendKeys "F"
Wscript.sleep 114
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 57
WshShell.SendKeys "E"
Wscript.sleep 28
WshShell.SendKeys "T"
Wscript.sleep 28
WshShell.SendKeys "D"
Wscript.sleep 342
WshShell.SendKeys "E"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 912
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "D"
Wscript.sleep 399
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "F"
Wscript.sleep 399
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "S"
Wscript.sleep 399
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 454
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 57
WshShell.SendKeys "G"
Wscript.sleep 912
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "A"
Wscript.sleep 57
WshShell.SendKeys "F"
Wscript.sleep 342
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 57
WshShell.SendKeys "F"
Wscript.sleep 399
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 57
WshShell.SendKeys "E"
Wscript.sleep 57
WshShell.SendKeys "T"
Wscript.sleep 342
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Z"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 1140
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "Z"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 456
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 1140
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Z"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 1140
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "R"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 114
WshShell.SendKeys "F"
Wscript.sleep 114
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 1140
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 456
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "W"
Wscript.sleep 684
WshShell.SendKeys "D"
Wscript.sleep 114
WshShell.SendKeys "F"
Wscript.sleep 114
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 456
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 114
WshShell.SendKeys "S"
Wscript.sleep 114
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "S"
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 228
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "B"
Wscript.sleep 456
WshShell.SendKeys "E"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "A"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 228
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 456
WshShell.SendKeys "Q"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 228
WshShell.SendKeys "T"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
Wscript.sleep 456
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 456
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 228
WshShell.SendKeys "D"
Wscript.sleep 228
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 1140
WshShell.SendKeys "A"
Wscript.sleep 285
WshShell.SendKeys "D"
Wscript.sleep 285
WshShell.SendKeys "X"
Wscript.sleep 285
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 570
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 570
WshShell.SendKeys "Q"
Wscript.sleep 285
WshShell.SendKeys "A"
Wscript.sleep 285
WshShell.SendKeys "D"
Wscript.sleep 285
WshShell.SendKeys "X"
Wscript.sleep 285
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 570
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 570
WshShell.SendKeys "T"
Wscript.sleep 570
WshShell.SendKeys "F"
Wscript.sleep 570
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 570
WshShell.SendKeys "T"
Wscript.sleep 570
WshShell.SendKeys "D"
Wscript.sleep 627
WshShell.SendKeys "Z"
Wscript.sleep 684
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
