Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 1000
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 900
WshShell.SendKeys "X"
Wscript.sleep 450
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 1350
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 900
WshShell.SendKeys "X"
Wscript.sleep 450
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 1200
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 900
WshShell.SendKeys "X"
Wscript.sleep 450
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 1200
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 1500
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "F"
Wscript.sleep 900
WshShell.SendKeys "R"
Wscript.sleep 450
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 450
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 1800
WshShell.SendKeys "Q"
WshShell.SendKeys "V"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 1500
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "R"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "D"
Wscript.sleep 450
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 1500
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 900
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "R"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 600
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 675
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 525
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 450
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 75
WshShell.SendKeys "R"
Wscript.sleep 75
WshShell.SendKeys "D"
Wscript.sleep 1500
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 750
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 750
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 900
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 75
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 75
WshShell.SendKeys "R"
Wscript.sleep 75
WshShell.SendKeys "A"
Wscript.sleep 1200
WshShell.SendKeys "W"
Wscript.sleep 75
WshShell.SendKeys "R"
Wscript.sleep 75
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 525
WshShell.SendKeys "T"
Wscript.sleep 525
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 600
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 450
WshShell.SendKeys "R"
Wscript.sleep 75
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 375
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 450
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "G"
Wscript.sleep 75
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 75
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 375
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 75
WshShell.SendKeys "D"
Wscript.sleep 75
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "F"
Wscript.sleep 262
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 262
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 262
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 375
WshShell.SendKeys "E"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 262
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 262
WshShell.SendKeys "S"
Wscript.sleep 262
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "E"
Wscript.sleep 750
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 262
WshShell.SendKeys "X"
WshShell.SendKeys "V"
Wscript.sleep 262
WshShell.SendKeys "W"
WshShell.SendKeys "C"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 750
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 375
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "A"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "F"
Wscript.sleep 937
WshShell.SendKeys "X"
Wscript.sleep 562
WshShell.SendKeys "B"
Wscript.sleep 562
WshShell.SendKeys "V"
Wscript.sleep 562
WshShell.SendKeys "R"
WshShell.SendKeys "B"
Wscript.sleep 375
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "T"
Wscript.sleep 450
WshShell.SendKeys "A"
Wscript.sleep 450
WshShell.SendKeys "D"
Wscript.sleep 450
WshShell.SendKeys "Z"
Wscript.sleep 450
WshShell.SendKeys "X"
Wscript.sleep 525
WshShell.SendKeys "C"
Wscript.sleep 525
WshShell.SendKeys "V"
Wscript.sleep 900
WshShell.SendKeys "B"
