Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 450
WshShell.SendKeys "Q"
Wscript.sleep 450
WshShell.SendKeys "E"
Wscript.sleep 600
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 450
WshShell.SendKeys "W"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 600
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "G"
Wscript.sleep 450
WshShell.SendKeys "A"
Wscript.sleep 450
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 375
WshShell.SendKeys "S"
Wscript.sleep 450
WshShell.SendKeys "C"
Wscript.sleep 525
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 450
WshShell.SendKeys "R"
Wscript.sleep 450
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 525
WshShell.SendKeys "E"
Wscript.sleep 450
WshShell.SendKeys "T"
Wscript.sleep 600
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 375
WshShell.SendKeys "D"
Wscript.sleep 375
WshShell.SendKeys "R"
Wscript.sleep 375
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 375
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 375
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Z"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 300
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "C"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "W"
Wscript.sleep 300
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "A"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 225
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "G"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 75
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "B"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "X"
Wscript.sleep 225
WshShell.SendKeys "Q"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "C"
Wscript.sleep 225
WshShell.SendKeys "W"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "F"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 300
WshShell.SendKeys "V"
Wscript.sleep 225
WshShell.SendKeys "V"
Wscript.sleep 375
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 225
WshShell.SendKeys "T"
Wscript.sleep 225
WshShell.SendKeys "D"
Wscript.sleep 225
WshShell.SendKeys "B"
