Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 4800
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 1000
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 800
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 400
WshShell.SendKeys "E"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "C"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "C"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 800
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 300
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 100
WshShell.SendKeys "Z"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 1200
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 300
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 600
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 600
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "Z"
Wscript.sleep 300
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "S"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 400
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 300
WshShell.SendKeys "R"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 400
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 300
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "Z"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "G"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 600
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "T"
Wscript.sleep 400
WshShell.SendKeys "A"
Wscript.sleep 400
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "C"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "C"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 200
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 100
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "Q"
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 200
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 100
WshShell.SendKeys "D"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 200
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "X"
Wscript.sleep 100
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 100
WshShell.SendKeys "G"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 200
WshShell.SendKeys "V"
Wscript.sleep 100
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 100
WshShell.SendKeys "V"
Wscript.sleep 200
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 200
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
