Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 700
WshShell.SendKeys "E"
Wscript.sleep 600
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 75
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "A"
Wscript.sleep 975
WshShell.SendKeys "D"
Wscript.sleep 600
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "C"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "X"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "R"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "V"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Z"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "D"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "S"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "W"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 150
WshShell.SendKeys "A"
Wscript.sleep 150
WshShell.SendKeys "E"
Wscript.sleep 150
WshShell.SendKeys "Q"
Wscript.sleep 300
WshShell.SendKeys "Q"
Wscript.sleep 75
WshShell.SendKeys "E"
Wscript.sleep 75
WshShell.SendKeys "A"
