Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 763
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 1452
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 1452
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 1452
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "A"
Wscript.sleep 726
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 363
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 726
WshShell.SendKeys "R"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "X"
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "Z"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "R"
Wscript.sleep 726
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "Z"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 726
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 726
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "S"
Wscript.sleep 726
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
WshShell.SendKeys "B"
Wscript.sleep 1089
WshShell.SendKeys "A"
Wscript.sleep 363
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "Z"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "Z"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 363
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 1089
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 1089
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 1089
WshShell.SendKeys "R"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 726
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "R"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "E"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "A"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 1089
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 1089
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 726
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 726
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 726
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "B"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "V"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "C"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "V"
Wscript.sleep 363
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 726
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 726
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 1089
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 1089
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
Wscript.sleep 363
WshShell.SendKeys "G"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "Q"
Wscript.sleep 363
WshShell.SendKeys "T"
Wscript.sleep 363
WshShell.SendKeys "S"
Wscript.sleep 363
WshShell.SendKeys "D"
Wscript.sleep 363
WshShell.SendKeys "X"
