Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 1328
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "R"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 498
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 166
WshShell.SendKeys "Z"
Wscript.sleep 83
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 166
WshShell.SendKeys "G"
Wscript.sleep 83
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 166
WshShell.SendKeys "X"
Wscript.sleep 83
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 415
WshShell.SendKeys "X"
Wscript.sleep 83
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 83
WshShell.SendKeys "D"
Wscript.sleep 83
WshShell.SendKeys "F"
Wscript.sleep 83
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 1328
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "R"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "V"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 498
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "S"
Wscript.sleep 498
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 498
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
Wscript.sleep 249
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 166
WshShell.SendKeys "F"
Wscript.sleep 83
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 498
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 332
WshShell.SendKeys "G"
Wscript.sleep 166
WshShell.SendKeys "W"
WshShell.SendKeys "R"
Wscript.sleep 166
WshShell.SendKeys "X"
Wscript.sleep 83
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 498
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "Z"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 498
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "R"
WshShell.SendKeys "F"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 332
WshShell.SendKeys "Z"
Wscript.sleep 83
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 166
WshShell.SendKeys "G"
Wscript.sleep 83
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 166
WshShell.SendKeys "X"
Wscript.sleep 83
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 415
WshShell.SendKeys "X"
Wscript.sleep 83
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "X"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "W"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 249
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 498
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "D"
Wscript.sleep 249
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 498
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "Q"
Wscript.sleep 249
WshShell.SendKeys "E"
Wscript.sleep 249
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 249
WshShell.SendKeys "T"
Wscript.sleep 83
WshShell.SendKeys "D"
Wscript.sleep 83
WshShell.SendKeys "F"
Wscript.sleep 83
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "X"
Wscript.sleep 498
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
