Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 918
WshShell.SendKeys "A"
Wscript.sleep 9
WshShell.SendKeys "D"
Wscript.sleep 10
WshShell.SendKeys "E"
Wscript.sleep 1017
WshShell.SendKeys "G"
Wscript.sleep 514
WshShell.SendKeys "S"
Wscript.sleep 12
WshShell.SendKeys "T"
Wscript.sleep 22
WshShell.SendKeys "W"
Wscript.sleep 994
WshShell.SendKeys "D"
Wscript.sleep 469
WshShell.SendKeys "R"
Wscript.sleep 11
WshShell.SendKeys "A"
Wscript.sleep 918
WshShell.SendKeys "D"
Wscript.sleep 504
WshShell.SendKeys "E"
Wscript.sleep 9
WshShell.SendKeys "T"
Wscript.sleep 854
WshShell.SendKeys "Q"
Wscript.sleep 508
WshShell.SendKeys "R"
Wscript.sleep 9
WshShell.SendKeys "W"
Wscript.sleep 446
WshShell.SendKeys "T"
Wscript.sleep 406
WshShell.SendKeys "A"
Wscript.sleep 456
WshShell.SendKeys "Q"
Wscript.sleep 92
WshShell.SendKeys "E"
Wscript.sleep 325
WshShell.SendKeys "A"
Wscript.sleep 526
WshShell.SendKeys "D"
Wscript.sleep 411
WshShell.SendKeys "W"
Wscript.sleep 13
WshShell.SendKeys "S"
Wscript.sleep 27
WshShell.SendKeys "F"
Wscript.sleep 9
WshShell.SendKeys "T"
Wscript.sleep 673
WshShell.SendKeys "S"
Wscript.sleep 184
WshShell.SendKeys "T"
Wscript.sleep 405
WshShell.SendKeys "A"
Wscript.sleep 9
WshShell.SendKeys "Q"
Wscript.sleep 83
WshShell.SendKeys "E"
Wscript.sleep 387
WshShell.SendKeys "E"
Wscript.sleep 461
WshShell.SendKeys "D"
Wscript.sleep 475
WshShell.SendKeys "S"
Wscript.sleep 887
WshShell.SendKeys "G"
Wscript.sleep 459
WshShell.SendKeys "B"
Wscript.sleep 27
WshShell.SendKeys "A"
Wscript.sleep 441
WshShell.SendKeys "D"
Wscript.sleep 10
WshShell.SendKeys "G"
Wscript.sleep 262
WshShell.SendKeys "B"
Wscript.sleep 188
WshShell.SendKeys "V"
Wscript.sleep 175
WshShell.SendKeys "C"
Wscript.sleep 183
WshShell.SendKeys "V"
Wscript.sleep 14
WshShell.SendKeys "T"
Wscript.sleep 208
WshShell.SendKeys "S"
Wscript.sleep 191
WshShell.SendKeys "F"
Wscript.sleep 543
WshShell.SendKeys "G"
Wscript.sleep 517
WshShell.SendKeys "R"
Wscript.sleep 10
WshShell.SendKeys "C"
Wscript.sleep 457
WshShell.SendKeys "A"
Wscript.sleep 11
WshShell.SendKeys "D"
Wscript.sleep 286
WshShell.SendKeys "C"
Wscript.sleep 180
WshShell.SendKeys "X"
Wscript.sleep 212
WshShell.SendKeys "Z"
Wscript.sleep 263
WshShell.SendKeys "X"
Wscript.sleep 14
WshShell.SendKeys "A"
Wscript.sleep 245
WshShell.SendKeys "E"
Wscript.sleep 188
WshShell.SendKeys "T"
Wscript.sleep 463
WshShell.SendKeys "D"
Wscript.sleep 495
WshShell.SendKeys "Z"
Wscript.sleep 8
WshShell.SendKeys "W"
Wscript.sleep 525
WshShell.SendKeys "R"
Wscript.sleep 8
WshShell.SendKeys "A"
Wscript.sleep 290
WshShell.SendKeys "Z"
Wscript.sleep 202
WshShell.SendKeys "G"
Wscript.sleep 227
WshShell.SendKeys "F"
Wscript.sleep 248
WshShell.SendKeys "E"
Wscript.sleep 9
WshShell.SendKeys "D"
Wscript.sleep 453
WshShell.SendKeys "A"
Wscript.sleep 11
WshShell.SendKeys "G"
Wscript.sleep 29
WshShell.SendKeys "D"
Wscript.sleep 519
WshShell.SendKeys "B"
Wscript.sleep 416
WshShell.SendKeys "W"
Wscript.sleep 102
WshShell.SendKeys "F"
Wscript.sleep 425
WshShell.SendKeys "A"
Wscript.sleep 12
WshShell.SendKeys "R"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 486
WshShell.SendKeys "S"
Wscript.sleep 8
WshShell.SendKeys "E"
Wscript.sleep 448
WshShell.SendKeys "E"
Wscript.sleep 454
WshShell.SendKeys "G"
Wscript.sleep 440
WshShell.SendKeys "B"
Wscript.sleep 9
WshShell.SendKeys "A"
Wscript.sleep 440
WshShell.SendKeys "D"
Wscript.sleep 11
WshShell.SendKeys "G"
Wscript.sleep 254
WshShell.SendKeys "B"
Wscript.sleep 190
WshShell.SendKeys "V"
Wscript.sleep 203
WshShell.SendKeys "C"
Wscript.sleep 175
WshShell.SendKeys "V"
Wscript.sleep 12
WshShell.SendKeys "T"
Wscript.sleep 242
WshShell.SendKeys "S"
Wscript.sleep 167
WshShell.SendKeys "F"
Wscript.sleep 542
WshShell.SendKeys "G"
Wscript.sleep 461
WshShell.SendKeys "C"
Wscript.sleep 13
WshShell.SendKeys "R"
Wscript.sleep 444
WshShell.SendKeys "A"
Wscript.sleep 29
WshShell.SendKeys "D"
Wscript.sleep 256
WshShell.SendKeys "C"
Wscript.sleep 212
WshShell.SendKeys "X"
Wscript.sleep 164
WshShell.SendKeys "Z"
Wscript.sleep 267
WshShell.SendKeys "X"
Wscript.sleep 18
WshShell.SendKeys "A"
Wscript.sleep 226
WshShell.SendKeys "E"
Wscript.sleep 178
WshShell.SendKeys "T"
Wscript.sleep 472
WshShell.SendKeys "D"
Wscript.sleep 472
WshShell.SendKeys "W"
Wscript.sleep 88
WshShell.SendKeys "Z"
Wscript.sleep 413
WshShell.SendKeys "A"
Wscript.sleep 26
WshShell.SendKeys "R"
Wscript.sleep 287
WshShell.SendKeys "Z"
Wscript.sleep 177
WshShell.SendKeys "G"
Wscript.sleep 251
WshShell.SendKeys "F"
Wscript.sleep 291
WshShell.SendKeys "D"
Wscript.sleep 14
WshShell.SendKeys "E"
Wscript.sleep 562
WshShell.SendKeys "A"
Wscript.sleep 16
WshShell.SendKeys "D"
Wscript.sleep 20
WshShell.SendKeys "G"
Wscript.sleep 409
WshShell.SendKeys "B"
Wscript.sleep 489
WshShell.SendKeys "S"
Wscript.sleep 9
WshShell.SendKeys "F"
Wscript.sleep 8
WshShell.SendKeys "T"
Wscript.sleep 114
WshShell.SendKeys "W"
Wscript.sleep 394
WshShell.SendKeys "S"
Wscript.sleep 503
WshShell.SendKeys "T"
Wscript.sleep 475
WshShell.SendKeys "Q"
Wscript.sleep 9
WshShell.SendKeys "A"
Wscript.sleep 85
WshShell.SendKeys "E"
Wscript.sleep 426
WshShell.SendKeys "Q"
Wscript.sleep 495
WshShell.SendKeys "D"
Wscript.sleep 1022
WshShell.SendKeys "Q"
Wscript.sleep 14
WshShell.SendKeys "G"
Wscript.sleep 506
WshShell.SendKeys "E"
Wscript.sleep 10
WshShell.SendKeys "T"
Wscript.sleep 267
WshShell.SendKeys "G"
Wscript.sleep 204
WshShell.SendKeys "Z"
Wscript.sleep 201
WshShell.SendKeys "G"
Wscript.sleep 216
WshShell.SendKeys "S"
Wscript.sleep 13
WshShell.SendKeys "F"
Wscript.sleep 240
WshShell.SendKeys "W"
Wscript.sleep 123
WshShell.SendKeys "T"
Wscript.sleep 382
WshShell.SendKeys "X"
Wscript.sleep 551
WshShell.SendKeys "E"
Wscript.sleep 86
WshShell.SendKeys "G"
Wscript.sleep 434
WshShell.SendKeys "A"
Wscript.sleep 23
WshShell.SendKeys "D"
Wscript.sleep 250
WshShell.SendKeys "G"
Wscript.sleep 150
WshShell.SendKeys "F"
Wscript.sleep 243
WshShell.SendKeys "D"
Wscript.sleep 206
WshShell.SendKeys "E"
Wscript.sleep 18
WshShell.SendKeys "S"
Wscript.sleep 177
WshShell.SendKeys "T"
Wscript.sleep 190
WshShell.SendKeys "S"
Wscript.sleep 545
WshShell.SendKeys "D"
Wscript.sleep 219
WshShell.SendKeys "S"
Wscript.sleep 220
WshShell.SendKeys "Q"
Wscript.sleep 25
WshShell.SendKeys "A"
Wscript.sleep 152
WshShell.SendKeys "R"
Wscript.sleep 356
WshShell.SendKeys "A"
Wscript.sleep 499
WshShell.SendKeys "S"
Wscript.sleep 262
WshShell.SendKeys "A"
Wscript.sleep 261
WshShell.SendKeys "Q"
Wscript.sleep 79
WshShell.SendKeys "T"
Wscript.sleep 443
WshShell.SendKeys "G"
Wscript.sleep 551
WshShell.SendKeys "D"
Wscript.sleep 410
WshShell.SendKeys "A"
Wscript.sleep 8
WshShell.SendKeys "W"
Wscript.sleep 248
WshShell.SendKeys "R"
Wscript.sleep 246
WshShell.SendKeys "A"
Wscript.sleep 14
WshShell.SendKeys "F"
Wscript.sleep 426
WshShell.SendKeys "A"
Wscript.sleep 557
WshShell.SendKeys "S"
Wscript.sleep 9
WshShell.SendKeys "E"
Wscript.sleep 523
WshShell.SendKeys "E"
Wscript.sleep 514
WshShell.SendKeys "G"
Wscript.sleep 462
WshShell.SendKeys "A"
Wscript.sleep 12
WshShell.SendKeys "B"
Wscript.sleep 500
WshShell.SendKeys "D"
Wscript.sleep 9
WshShell.SendKeys "G"
Wscript.sleep 243
WshShell.SendKeys "B"
Wscript.sleep 173
WshShell.SendKeys "V"
Wscript.sleep 230
WshShell.SendKeys "C"
Wscript.sleep 185
WshShell.SendKeys "V"
Wscript.sleep 27
WshShell.SendKeys "T"
Wscript.sleep 254
WshShell.SendKeys "S"
Wscript.sleep 204
WshShell.SendKeys "F"
Wscript.sleep 576
WshShell.SendKeys "G"
Wscript.sleep 443
WshShell.SendKeys "R"
Wscript.sleep 11
WshShell.SendKeys "C"
Wscript.sleep 479
WshShell.SendKeys "A"
Wscript.sleep 8
WshShell.SendKeys "D"
Wscript.sleep 262
WshShell.SendKeys "C"
Wscript.sleep 216
WshShell.SendKeys "X"
Wscript.sleep 189
WshShell.SendKeys "Z"
Wscript.sleep 254
WshShell.SendKeys "X"
Wscript.sleep 14
WshShell.SendKeys "A"
Wscript.sleep 263
WshShell.SendKeys "E"
Wscript.sleep 170
WshShell.SendKeys "T"
Wscript.sleep 590
WshShell.SendKeys "D"
Wscript.sleep 426
WshShell.SendKeys "Z"
Wscript.sleep 35
WshShell.SendKeys "W"
Wscript.sleep 507
WshShell.SendKeys "A"
Wscript.sleep 11
WshShell.SendKeys "R"
Wscript.sleep 277
WshShell.SendKeys "Z"
Wscript.sleep 246
WshShell.SendKeys "G"
Wscript.sleep 207
WshShell.SendKeys "F"
Wscript.sleep 408
WshShell.SendKeys "D"
Wscript.sleep 12
WshShell.SendKeys "E"
Wscript.sleep 591
WshShell.SendKeys "A"
Wscript.sleep 12
WshShell.SendKeys "G"
Wscript.sleep 8
WshShell.SendKeys "D"
Wscript.sleep 488
WshShell.SendKeys "B"
Wscript.sleep 442
WshShell.SendKeys "W"
Wscript.sleep 26
WshShell.SendKeys "F"
Wscript.sleep 551
WshShell.SendKeys "A"
Wscript.sleep 64
WshShell.SendKeys "R"
Wscript.sleep 473
WshShell.SendKeys "A"
Wscript.sleep 519
WshShell.SendKeys "E"
Wscript.sleep 11
WshShell.SendKeys "S"
Wscript.sleep 541
WshShell.SendKeys "E"
Wscript.sleep 515
WshShell.SendKeys "G"
Wscript.sleep 484
WshShell.SendKeys "B"
Wscript.sleep 24
WshShell.SendKeys "A"
Wscript.sleep 479
WshShell.SendKeys "D"
Wscript.sleep 9
WshShell.SendKeys "G"
Wscript.sleep 293
WshShell.SendKeys "B"
Wscript.sleep 158
WshShell.SendKeys "V"
Wscript.sleep 244
WshShell.SendKeys "C"
Wscript.sleep 180
WshShell.SendKeys "V"
Wscript.sleep 17
WshShell.SendKeys "T"
Wscript.sleep 262
WshShell.SendKeys "S"
Wscript.sleep 172
WshShell.SendKeys "F"
Wscript.sleep 571
WshShell.SendKeys "G"
Wscript.sleep 508
WshShell.SendKeys "R"
Wscript.sleep 9
WshShell.SendKeys "C"
Wscript.sleep 434
WshShell.SendKeys "A"
Wscript.sleep 39
WshShell.SendKeys "D"
Wscript.sleep 306
WshShell.SendKeys "C"
Wscript.sleep 215
WshShell.SendKeys "X"
Wscript.sleep 187
WshShell.SendKeys "Z"
Wscript.sleep 256
WshShell.SendKeys "X"
Wscript.sleep 17
WshShell.SendKeys "A"
Wscript.sleep 256
WshShell.SendKeys "E"
Wscript.sleep 175
WshShell.SendKeys "T"
Wscript.sleep 479
WshShell.SendKeys "D"
Wscript.sleep 491
WshShell.SendKeys "Z"
Wscript.sleep 12
WshShell.SendKeys "W"
Wscript.sleep 532
WshShell.SendKeys "A"
Wscript.sleep 15
WshShell.SendKeys "R"
Wscript.sleep 318
WshShell.SendKeys "Z"
Wscript.sleep 262
WshShell.SendKeys "G"
Wscript.sleep 329
WshShell.SendKeys "F"
Wscript.sleep 367
WshShell.SendKeys "D"
Wscript.sleep 12
WshShell.SendKeys "E"
Wscript.sleep 645
WshShell.SendKeys "G"
Wscript.sleep 10
WshShell.SendKeys "A"
Wscript.sleep 10
WshShell.SendKeys "D"
Wscript.sleep 608
WshShell.SendKeys "B"
Wscript.sleep 685
WshShell.SendKeys "S"
Wscript.sleep 10
WshShell.SendKeys "T"
Wscript.sleep 7
WshShell.SendKeys "F"
Wscript.sleep 115
WshShell.SendKeys "W"
Wscript.sleep 495
WshShell.SendKeys "S"
Wscript.sleep 664
WshShell.SendKeys "T"
Wscript.sleep 653
WshShell.SendKeys "Q"
Wscript.sleep 11
WshShell.SendKeys "A"
Wscript.sleep 84
WshShell.SendKeys "E"
