Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
Wscript.sleep 1056
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 1188
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 1188
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 594
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 264
WshShell.SendKeys "F"
Wscript.sleep 132
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "E"
Wscript.sleep 198
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 132
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 594
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 264
WshShell.SendKeys "F"
Wscript.sleep 132
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "E"
Wscript.sleep 198
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 792
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "D"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "A"
Wscript.sleep 264
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 396
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 594
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 264
WshShell.SendKeys "F"
Wscript.sleep 132
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "E"
Wscript.sleep 198
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 792
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "D"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "A"
Wscript.sleep 264
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 396
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 594
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 264
WshShell.SendKeys "F"
Wscript.sleep 132
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "E"
Wscript.sleep 198
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 792
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "D"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "A"
Wscript.sleep 264
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 396
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 594
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "R"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "T"
Wscript.sleep 264
WshShell.SendKeys "F"
Wscript.sleep 132
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "Q"
Wscript.sleep 198
WshShell.SendKeys "E"
Wscript.sleep 198
WshShell.SendKeys "T"
Wscript.sleep 198
WshShell.SendKeys "D"
Wscript.sleep 198
WshShell.SendKeys "G"
Wscript.sleep 198
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 792
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 594
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 198
WshShell.SendKeys "A"
WshShell.SendKeys "C"
Wscript.sleep 396
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 396
WshShell.SendKeys "R"
WshShell.SendKeys "Z"
Wscript.sleep 396
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 396
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 528
WshShell.SendKeys "S"
Wscript.sleep 132
WshShell.SendKeys "D"
Wscript.sleep 132
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 396
WshShell.SendKeys "F"
Wscript.sleep 264
WshShell.SendKeys "G"
Wscript.sleep 132
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 792
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
