Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "C"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 420
WshShell.SendKeys "E"
Wscript.sleep 630
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 840
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 420
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 630
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "R"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 1680
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 420
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "C"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 420
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 420
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "C"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "C"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 420
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 840
WshShell.SendKeys "T"
Wscript.sleep 840
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 420
WshShell.SendKeys "V"
Wscript.sleep 420
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 210
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 630
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 420
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 420
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "E"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "B"
Wscript.sleep 420
WshShell.SendKeys "V"
Wscript.sleep 420
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 840
WshShell.SendKeys "S"
Wscript.sleep 840
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 630
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 840
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 420
WshShell.SendKeys "E"
WshShell.SendKeys "D"
Wscript.sleep 840
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 420
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
Wscript.sleep 420
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "R"
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 630
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 840
WshShell.SendKeys "T"
WshShell.SendKeys "D"
Wscript.sleep 420
WshShell.SendKeys "W"
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 840
WshShell.SendKeys "X"
Wscript.sleep 840
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
Wscript.sleep 1470
WshShell.SendKeys "A"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 420
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 420
WshShell.SendKeys "G"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "Z"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "S"
WshShell.SendKeys "F"
Wscript.sleep 420
WshShell.SendKeys "A"
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "E"
Wscript.sleep 210
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "B"
Wscript.sleep 210
WshShell.SendKeys "F"
WshShell.SendKeys "V"
Wscript.sleep 210
WshShell.SendKeys "D"
WshShell.SendKeys "X"
Wscript.sleep 420
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "Q"
Wscript.sleep 210
WshShell.SendKeys "R"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "C"
Wscript.sleep 420
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "D"
Wscript.sleep 210
WshShell.SendKeys "T"
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "W"
Wscript.sleep 210
WshShell.SendKeys "T"
Wscript.sleep 210
WshShell.SendKeys "S"
Wscript.sleep 210
WshShell.SendKeys "F"
Wscript.sleep 210
WshShell.SendKeys "X"
Wscript.sleep 210
WshShell.SendKeys "V"
Wscript.sleep 420
WshShell.SendKeys "B"
Wscript.sleep 1680
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
