Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.AppActivate "Pixel 2 XL"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 544
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 544
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 408
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 272
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "T"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 408
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 272
WshShell.SendKeys "T"
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "R"
WshShell.SendKeys "R"
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "E"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "T"
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "Q"
WshShell.SendKeys "E"
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "W"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "B"
WshShell.SendKeys "B"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "T"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "S"
WshShell.SendKeys "S"
WshShell.SendKeys "X"
WshShell.SendKeys "X"
Wscript.sleep 136
WshShell.SendKeys "T"
Wscript.sleep 136
WshShell.SendKeys "S"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 136
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "A"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "W"
WshShell.SendKeys "A"
Wscript.sleep 136
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "W"
Wscript.sleep 136
WshShell.SendKeys "W"
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 272
WshShell.SendKeys "W"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 136
WshShell.SendKeys "F"
WshShell.SendKeys "F"
Wscript.sleep 136
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
Wscript.sleep 272
WshShell.SendKeys "Q"
WshShell.SendKeys "A"
WshShell.SendKeys "D"
WshShell.SendKeys "D"
Wscript.sleep 272
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "A"
Wscript.sleep 544
WshShell.SendKeys "E"
Wscript.sleep 136
WshShell.SendKeys "W"
Wscript.sleep 136
WshShell.SendKeys "Q"
Wscript.sleep 136
WshShell.SendKeys "S"
Wscript.sleep 136
WshShell.SendKeys "E"
WshShell.SendKeys "A"
WshShell.SendKeys "G"
WshShell.SendKeys "G"
WshShell.SendKeys "C"
WshShell.SendKeys "C"
